/* ============================================================
   ONE PIECE DLE — base de personnages
   GÉNÉRÉ depuis One Piece Encyclopédie (onepiece.fandom.com/fr).
   Ne pas éditer à la main : les indices emoji vivent dans js/emoji.js,
   la sélection dans tools/selection.txt.

   [ nom, genre, equipage, camp, fruit, haki, prime, taille, origine, arc ]

   prime : berries — -1 = non révélée (la dernière prime connue est
           retenue pour les personnages morts, capturés ou graciés)
   taille : cm, -1 = non révélée
   arc    : arc de première apparition, déduit du numéro de chapitre
   ============================================================ */

const ARCS = [
  "Romance Dawn",
  "Ville d'Orange",
  "Village de Syrup",
  "Baratie",
  "Arlong Park",
  "Loguetown",
  "Reverse Mountain",
  "Whisky Peak",
  "Little Garden",
  "Drum",
  "Alabasta",
  "Jaya",
  "Skypiea",
  "Long Ring Long Land",
  "Water 7",
  "Enies Lobby",
  "Post-Enies Lobby",
  "Thriller Bark",
  "Sabaody",
  "Amazon Lily",
  "Impel Down",
  "Marineford",
  "Après-guerre",
  "Retour à Sabaody",
  "Ile des Hommes-Poissons",
  "Punk Hazard",
  "Dressrosa",
  "Zou",
  "Whole Cake Island",
  "Reverie",
  "Wano",
  "Egghead",
  "Elbaf"
  ];

const RAW_CHARACTERS = [
["Abdullah et Jeet", "M", "Équipage d'Ideo", "Pirate", "Aucun", "", 50000000, -1, "Inconnue", "Dressrosa"],
["Absalom", "M", "Gecko Moria", "Civil", "Paramecia", "", -1, 195, "West Blue", "Thriller Bark"],
["Aisa", "F", "Shandia", "Civil", "Aucun", "O", -1, 140, "Ciel", "Skypiea"],
["Akainu", "M", "Marines", "Marine", "Logia", "AO", 4000000000, 306, "North Blue", "Enies Lobby"],
["Aladdin", "M", "Équipage des Pirates du Soleil", "Pirate", "Aucun", "", -1, 627, "Ile des Hommes-Poissons", "Ile des Hommes-Poissons"],
["Alvida", "F", "Alliance Baggy et Alvida", "Civil", "Paramecia", "", 5000000, 198, "East Blue", "Romance Dawn"],
["Aokiji", "M", "Équipage de Barbe Noire", "Pirate", "Logia", "AO", -1, 298, "South Blue", "Long Ring Long Land"],
["Aphelandra", "F", "Kujas", "Pirate", "Aucun", "A", -1, -1, "Calm Belt", "Amazon Lily"],
["Arlong", "M", "Équipage d'Arlong", "Pirate", "Aucun", "", 20000000, 263, "Ile des Hommes-Poissons", "Arlong Park"],
["Ashura Doji", "M", "Voleurs d'Atamayama", "Civil", "Aucun", "AO", -1, 544, "Inconnue", "Wano"],
["Atlas", "F", "Gouvernement Mondial", "Gouvernement", "Aucun", "", -1, 729, "Inconnue", "Egghead"],
["Atmos", "M", "L'Équipage de Barbe Blanche", "Pirate", "Aucun", "", -1, -1, "West Blue", "Marineford"],
["Avalo Pizarro", "M", "Équipage de Barbe Noire", "Pirate", "Paramecia", "", 100000000, 505, "North Blue", "Marineford"],
["Babanuki", "M", "Équipage des cent bêtes", "Pirate", "Aucun", "", -1, -1, "Inconnue", "Wano"],
["Baby 5", "F", "Flotte de Happou", "Civil", "Paramecia", "", -1, 181, "North Blue", "Punk Hazard"],
["Bao Huang", "F", "Équipage des cent bêtes", "Pirate", "Aucun", "", -1, -1, "Inconnue", "Wano"],
["Barbe Blanche", "M", "L'Équipage de Barbe Blanche", "Pirate", "Paramecia", "AOR", 5046000000, 666, "Inconnue", "Jaya"],
["Barbe Brune", "M", "L'Équipage de Barbe Brune", "Pirate", "Aucun", "", 80060000, 691, "Grand Line", "Après-guerre"],
["Barbe Noire", "M", "Équipage de Barbe Noire", "Pirate", "Logia", "AO", 3996000000, 344, "Grand Line", "Jaya"],
["Bartholomew Kuma", "M", "Pirates/Sept grands corsaires", "Pirate", "Paramecia", "O", 296000000, 689, "South Blue", "Jaya"],
["Bartolomeo", "M", "L'Équipage de Bartolomeo", "Pirate", "Paramecia", "", 150000000, 220, "East Blue", "Dressrosa"],
["Basil Hawkins", "M", "Équipage de Hawkins", "Pirate", "Paramecia", "AO", 320000000, 210, "North Blue", "Sabaody"],
["Bastille", "M", "Marines", "Marine", "Aucun", "AO", -1, 291, "Grand Line", "Marineford"],
["Bellamy", "M", "Équipage de Bellamy", "Pirate", "Paramecia", "AO", 195000000, 240, "North Blue", "Jaya"],
["Bellemere", "F", "Marines", "Marine", "Aucun", "", -1, 186, "East Blue", "Arlong Park"],
["Belo Betty", "F", "Révolutionnaires", "Revolutionnaire", "Paramecia", "AO", 457000000, 196, "East Blue", "Reverie"],
["Benn Beckman", "M", "L'Équipage du Roux", "Pirate", "Aucun", "AO", -1, 206, "North Blue", "Romance Dawn"],
["Bepo", "M", "Équipage du Heart", "Pirate", "Aucun", "", 1500, 240, "Grand Line", "Sabaody"],
["Big Mom", "F", "Équipage de Big Mom", "Pirate", "Paramecia", "AOR", 4388000000, 880, "Grand Line", "Ile des Hommes-Poissons"],
["Big Pan", "M", "L'Équipage de Foxy", "Pirate", "Aucun", "", -1, -1, "Inconnue", "Long Ring Long Land"],
["Black Maria", "F", "Équipage des cent bêtes", "Pirate", "Zoan Ancestral", "AO", 480000000, 820, "Wano", "Wano"],
["Blue Gilly", "M", "Équipage d'Ideo", "Pirate", "Aucun", "", -1, 314, "Grand Line", "Dressrosa"],
["Bluejam", "M", "L'Équipage de Bluejam", "Pirate", "Aucun", "", 14300000, 261, "Inconnue", "Après-guerre"],
["Blueno", "M", "CP-AIGIS0", "Gouvernement", "Paramecia", "AO", -1, 258, "North Blue", "Water 7"],
["Boa Hancock", "F", "Kujas", "Pirate", "Paramecia", "AOR", 1659000000, 191, "Calm Belt", "Amazon Lily"],
["Boa Marigold", "F", "Kujas", "Pirate", "Zoan", "AO", 40000000, 432, "Calm Belt", "Amazon Lily"],
["Boa Sandersonia", "F", "Kujas", "Pirate", "Zoan", "AO", 40000000, 453, "Calm Belt", "Amazon Lily"],
["Bobby Funk", "M", "Colisée Corrida", "Civil", "Aucun", "", 36000000, 320, "Inconnue", "Dressrosa"],
["Bogart", "M", "Marines", "Marine", "Aucun", "", -1, -1, "Inconnue", "Arlong Park"],
["Boo", "M", "Flotte de Happou", "Civil", "Aucun", "A", 50000000, -1, "Inconnue", "Dressrosa"],
["Braham", "M", "Shandia", "Civil", "Aucun", "", -1, 179, "Ciel", "Skypiea"],
["Brannew", "M", "Marines", "Marine", "Aucun", "", -1, 190, "Grand Line", "Loguetown"],
["Brogy", "M", "L'Équipage des Géants", "Pirate", "Aucun", "", 1800000000, 2130, "Elbaf", "Little Garden"],
["Brook", "M", "Équipage du Chapeau de Paille", "Pirate", "Paramecia", "", 383000000, 277, "West Blue", "Thriller Bark"],
["Buchi", "M", "Équipage du Chat Noir", "Pirate", "Aucun", "", 7000000, 216, "East Blue", "Village de Syrup"],
["Buckingham Stussy", "F", "Edward Weeble", "Civil", "Aucun", "", -1, 76, "Grand Line", "Zou"],
["Buddle", "M", "Orange Town", "Civil", "Aucun", "", -1, 172, "Inconnue", "Ville d'Orange"],
["Buffalo", "M", "Équipage de Don Quijote", "Pirate", "Paramecia", "", -1, 696, "North Blue", "Punk Hazard"],
["Buggy", "M", "Cross Guild", "Civil", "Paramecia", "", 3189000000, 192, "Grand Line", "Ville d'Orange"],
["Cabaji", "M", "L'Équipage du Clown", "Pirate", "Aucun", "", -1, 208, "East Blue", "Ville d'Orange"],
["Caesar Clown", "M", "Néo Mads", "Civil", "Logia", "", 300000000, 309, "Grand Line", "Punk Hazard"],
["Camie", "F", "Takoyaki 8", "Civil", "Aucun", "", -1, 197, "Inconnue", "Alabasta"],
["Capone Bege", "M", "Équipage du Fire Tank", "Pirate", "Paramecia", "A", 350000000, 166, "West Blue", "Sabaody"],
["Caribou", "M", "Équipage de Caribou", "Pirate", "Logia", "", 210000000, 228, "North Blue", "Retour à Sabaody"],
["Carotte", "M", "Équipage du Capitaine Usopp", "Pirate", "Aucun", "", -1, 127, "Inconnue", "Village de Syrup"],
["Carrot", "F", "Zou", "Civil", "Aucun", "", -1, 161, "Grand Line", "Zou"],
["Catarina Devon", "F", "Équipage de Barbe Noire", "Pirate", "Zoan Mythique", "", 100000000, 361, "South Blue", "Marineford"],
["Cavendish", "M", "Équipage des Jolis Pirates", "Pirate", "Aucun", "", 330000000, 208, "Grand Line", "Dressrosa"],
["Chaka", "M", "Alabasta", "Civil", "Zoan", "", -1, 213, "Inconnue", "Alabasta"],
["Charlotte Amande", "F", "Équipage de Big Mom", "Pirate", "Aucun", "", -1, -1, "Inconnue", "Whole Cake Island"],
["Charlotte Basskarte", "M", "Famille Charlotte", "Pirate", "Aucun", "", -1, -1, "Inconnue", "Whole Cake Island"],
["Charlotte Bavarois", "M", "Famille Charlotte", "Pirate", "Aucun", "", -1, -1, "Inconnue", "Whole Cake Island"],
["Charlotte Brownie", "M", "Équipage de Big Mom", "Pirate", "Aucun", "", -1, -1, "Inconnue", "Whole Cake Island"],
["Charlotte Broyée", "F", "Famille Charlotte", "Pirate", "Aucun", "", -1, -1, "Grand Line", "Whole Cake Island"],
["Charlotte Brulee", "F", "Famille Charlotte", "Pirate", "Paramecia", "", -1, 350, "Grand Line", "Whole Cake Island"],
["Charlotte Cabaletta", "M", "Famille Charlotte", "Pirate", "Aucun", "A", -1, -1, "Inconnue", "Whole Cake Island"],
["Charlotte Cadenza", "M", "Famille Charlotte", "Pirate", "Aucun", "A", -1, -1, "Inconnue", "Whole Cake Island"],
["Charlotte Chiboust", "M", "Famille Charlotte", "Pirate", "Aucun", "", -1, -1, "Inconnue", "Whole Cake Island"],
["Charlotte Chiffon", "F", "Famille Charlotte", "Pirate", "Aucun", "", -1, 215, "Grand Line", "Whole Cake Island"],
["Charlotte Cinnamon", "F", "Famille Charlotte", "Pirate", "Aucun", "", -1, -1, "Grand Line", "Whole Cake Island"],
["Charlotte Citron", "F", "Famille Charlotte", "Pirate", "Aucun", "", -1, -1, "Grand Line", "Whole Cake Island"],
["Charlotte Compo", "M", "Équipage de Big Mom", "Pirate", "Aucun", "", -1, -1, "Inconnue", "Whole Cake Island"],
["Charlotte Compote", "F", "Famille Charlotte", "Pirate", "Aucun", "", -1, -1, "Inconnue", "Whole Cake Island"],
["Charlotte Counter", "M", "Famille Charlotte", "Pirate", "Aucun", "A", -1, -1, "Inconnue", "Whole Cake Island"],
["Charlotte Cracker", "M", "Famille Charlotte", "Pirate", "Paramecia", "AO", 860000000, 307, "Grand Line", "Whole Cake Island"],
["Charlotte Dacquoise", "M", "Famille Charlotte", "Pirate", "Aucun", "", -1, -1, "Inconnue", "Whole Cake Island"],
["Charlotte Daifuku", "M", "Famille Charlotte", "Pirate", "Paramecia", "AO", 300000000, 489, "Grand Line", "Whole Cake Island"],
["Charlotte Effilée", "F", "Équipage de Big Mom", "Pirate", "Aucun", "", -1, -1, "Inconnue", "Whole Cake Island"],
["Charlotte Flampe", "F", "Famille Charlotte", "Pirate", "Aucun", "", -1, 170, "Grand Line", "Whole Cake Island"],
["Charlotte Galette", "F", "Famille Charlotte", "Pirate", "Paramecia", "", -1, -1, "Inconnue", "Whole Cake Island"],
["Charlotte High Fat", "M", "Équipage de Big Mom", "Pirate", "Aucun", "", -1, -1, "Inconnue", "Whole Cake Island"],
["Charlotte Joscarpone", "F", "Famille Charlotte", "Pirate", "Aucun", "", -1, -1, "Inconnue", "Whole Cake Island"],
["Charlotte Katakuri", "M", "Équipage de Big Mom", "Pirate", "Paramecia", "AOR", 1057000000, 509, "Grand Line", "Whole Cake Island"],
["Charlotte Laura", "F", "L'Équipage du Rolling", "Pirate", "Aucun", "", 24000000, 215, "Grand Line", "Thriller Bark"],
["Charlotte Laura/Forme Zombie", "F", "Thriller Bark", "Pirate", "Aucun", "", -1, -1, "Inconnue", "Thriller Bark"],
["Charlotte Laurique", "M", "Équipage de Big Mom", "Pirate", "Aucun", "", -1, -1, "Inconnue", "Whole Cake Island"],
["Charlotte Mascarpone", "M", "Famille Charlotte", "Pirate", "Aucun", "", -1, -1, "Inconnue", "Whole Cake Island"],
["Charlotte Mobile", "M", "Équipage de Big Mom", "Pirate", "Aucun", "", -1, -1, "Inconnue", "Whole Cake Island"],
["Charlotte Mont d'Or", "M", "Équipage de Big Mom", "Pirate", "Paramecia", "", 120000000, 260, "Grand Line", "Whole Cake Island"],
["Charlotte Mont-blanc", "M", "Famille Charlotte", "Pirate", "Aucun", "", -1, -1, "Inconnue", "Whole Cake Island"],
["Charlotte Mucre", "F", "Équipage de Big Mom", "Pirate", "Aucun", "", -1, -1, "Inconnue", "Whole Cake Island"],
["Charlotte Noisette", "M", "Famille Charlotte", "Pirate", "Aucun", "", -1, -1, "Inconnue", "Whole Cake Island"],
["Charlotte Nusstorte", "M", "Famille Charlotte", "Pirate", "Aucun", "", -1, -1, "Inconnue", "Whole Cake Island"],
["Charlotte Opéra", "M", "Famille Charlotte", "Pirate", "Paramecia", "", -1, -1, "Inconnue", "Whole Cake Island"],
["Charlotte Oven", "M", "Famille Charlotte", "Pirate", "Paramecia", "AO", 300000000, 492, "Grand Line", "Whole Cake Island"],
["Charlotte Perospero", "M", "Famille Charlotte", "Pirate", "Paramecia", "AO", 700000000, 333, "Grand Line", "Whole Cake Island"],
["Charlotte Poire", "F", "Famille Charlotte", "Pirate", "Aucun", "", -1, -1, "Inconnue", "Whole Cake Island"],
["Charlotte Praline", "F", "Famille Charlotte", "Pirate", "Aucun", "", -1, 800, "Inconnue", "Whole Cake Island"],
["Charlotte Prim", "F", "Famille Charlotte", "Pirate", "Aucun", "", -1, -1, "Inconnue", "Whole Cake Island"],
["Charlotte Pudding", "F", "Famille Charlotte", "Pirate", "Paramecia", "", -1, 166, "Inconnue", "Ile des Hommes-Poissons"],
["Charlotte Raisin", "M", "Famille Charlotte", "Pirate", "Aucun", "A", -1, -1, "Inconnue", "Whole Cake Island"],
["Charlotte Saint-Marc", "M", "Famille Charlotte", "Pirate", "Aucun", "", -1, -1, "Inconnue", "Whole Cake Island"],
["Charlotte Smoothie", "F", "Famille Charlotte", "Pirate", "Paramecia", "AO", 932000000, 464, "Grand Line", "Whole Cake Island"],
["Charlotte Snack", "M", "Équipage de Big Mom", "Pirate", "Aucun", "A", 600000000, -1, "Inconnue", "Whole Cake Island"],
["Charlotte Sucrage", "M", "Famille Charlotte", "Pirate", "Aucun", "", -1, -1, "Inconnue", "Whole Cake Island"],
["Charlotte Tablette", "M", "Équipage de Big Mom", "Pirate", "Aucun", "", -1, -1, "Inconnue", "Whole Cake Island"],
["Charlotte Yu Yuan", "M", "Famille Charlotte", "Pirate", "Aucun", "", -1, -1, "Inconnue", "Whole Cake Island"],
["Charlotte Zuccotto", "M", "Équipage de Big Mom", "Pirate", "Aucun", "", -1, -1, "Inconnue", "Whole Cake Island"],
["Chew", "M", "Équipage d'Arlong", "Pirate", "Aucun", "", 5500000, 257, "Ile des Hommes-Poissons", "Arlong Park"],
["Chimney", "F", "Gare de Shift", "Civil", "Aucun", "", -1, 115, "Inconnue", "Water 7"],
["Chinjao", "M", "Famille Chinjao", "Civil", "Aucun", "AOR", 542000000, 520, "Inconnue", "Dressrosa"],
["Chouchou", "M", "Hokker", "Civil", "Aucun", "", -1, 40, "Inconnue", "Ville d'Orange"],
["Claw D. Clover", "M", "Archéologue", "Civil", "Aucun", "", -1, 172, "West Blue", "Enies Lobby"],
["Conis", "F", "Café Potiron", "Civil", "Aucun", "", -1, 176, "Ciel", "Skypiea"],
["Conney", "F", "Royaume de Sorbet", "Civil", "Aucun", "", -1, 73, "Inconnue", "Egghead"],
["Coribou", "M", "Équipage de Caribou", "Pirate", "Aucun", "", 190000000, 250, "North Blue", "Retour à Sabaody"],
["Crocodile", "M", "Cross Guild", "Civil", "Logia", "AO", 1965000000, 253, "Grand Line", "Little Garden"],
["Crocus", "M", "Phare du Cap des Jumeaux", "Civil", "Aucun", "O", -1, 203, "Grand Line", "Reverse Mountain"],
["Curly Dadan", "F", "Bandits#Bandits des montagnes", "Civil", "Aucun", "", 7800000, 221, "East Blue", "Après-guerre"],
["Dagama", "M", "Royaume de Prodence", "Civil", "Aucun", "", -1, -1, "Inconnue", "Dressrosa"],
["Dalmatien", "M", "Marines", "Marine", "Zoan", "", -1, -1, "Inconnue", "Marineford"],
["Daruma", "M", "Nouvel équipage des hommes-poissons", "Pirate", "Aucun", "", -1, 122, "Ile des Hommes-Poissons", "Ile des Hommes-Poissons"],
["Davy D. Jones", "M", "Famille Davy", "Civil", "Aucun", "", -1, -1, "Inconnue", "Long Ring Long Land"],
["Daz Bones", "M", "Cross Guild", "Civil", "Paramecia", "", 75000000, 212, "West Blue", "Alabasta"],
["Dellinger", "M", "Équipage de Don Quijote", "Pirate", "Aucun", "", 15000000, -1, "North Blue", "Dressrosa"],
["Demalo Black", "M", "Faux Équipage du Chapeau de Paille", "Pirate", "Aucun", "", 26000000, 245, "East Blue", "Retour à Sabaody"],
["Den", "M", "Civil", "Civil", "Aucun", "", -1, 435, "Ile des Hommes-Poissons", "Ile des Hommes-Poissons"],
["Denjiro", "M", "Pays des Wa", "Samourai", "Aucun", "AO", -1, 306, "Wano", "Wano"],
["Diamante", "M", "Équipage de Don Quijote", "Pirate", "Paramecia", "AO", 99000000, 525, "North Blue", "Dressrosa"],
["Diesel", "M", "Équipage de Big Mom", "Pirate", "Aucun", "", -1, -1, "Inconnue", "Whole Cake Island"],
["Doberman", "M", "Marines", "Marine", "Aucun", "", -1, -1, "Inconnue", "Enies Lobby"],
["Doc Q", "M", "Équipage de Barbe Noire", "Pirate", "Paramecia", "", 72000000, 342, "North Blue", "Jaya"],
["Dolton", "M", "Royaume des Cerisiers", "Civil", "Zoan", "", -1, 218, "Inconnue", "Drum"],
["Doma", "M", "L'Équipage de Barbe Blanche", "Pirate", "Aucun", "", -1, -1, "Inconnue", "Marineford"],
["Domino", "F", "Impel Down", "Gouvernement", "Aucun", "", -1, -1, "Grand Line", "Impel Down"],
["Don Krieg", "M", "Armada de Don Krieg", "Civil", "Aucun", "", 17000000, 243, "Inconnue", "Baratie"],
["Don Quichotte Rossinante", "M", "Équipage de Don Quijote", "Pirate", "Paramecia", "", -1, 293, "Inconnue", "Dressrosa"],
["Donquixote Doflamingo", "M", "Équipage de Don Quijote", "Pirate", "Paramecia", "AOR", 340000000, 305, "Inconnue", "Jaya"],
["Dorry", "M", "L'Équipage des Géants", "Pirate", "Aucun", "", 1800000000, 2260, "Elbaf", "Little Garden"],
["Dosun", "M", "Nouvel équipage des hommes-poissons", "Pirate", "Aucun", "", -1, 418, "Ile des Hommes-Poissons", "Ile des Hommes-Poissons"],
["Dr. Hiluluk", "M", "Royaume des Cerisiers", "Civil", "Aucun", "", -1, 213, "Inconnue", "Drum"],
["Dr. Kureha", "F", "Royaume des Cerisiers", "Civil", "Aucun", "", -1, 188, "Grand Line", "Drum"],
["Dracule Mihawk", "M", "Cross Guild", "Civil", "Aucun", "AO", 3590000000, 198, "Inconnue", "Baratie"],
["Duval", "M", "Rosy Life Riders", "Civil", "Aucun", "", -1, 470, "Inconnue", "Sabaody"],
["Edison", "?", "Gouvernement Mondial", "Gouvernement", "Aucun", "", -1, 100, "Inconnue", "Egghead"],
["Edward Weevil", "M", "Pirates/Sept grands corsaires", "Pirate", "Aucun", "AO", 480000000, 680, "Grand Line", "Zou"],
["Elizabello II", "M", "Royaume de Prodence", "Civil", "Aucun", "", -1, 436, "Inconnue", "Dressrosa"],
["Emporio Ivankov", "?", "Armée Révolutionnaire", "Revolutionnaire", "Paramecia", "", 100000000, 449, "Grand Line", "Impel Down"],
["Enel", "M", "Clan d'Ener", "Civil", "Logia", "O", -1, 266, "Ciel", "Skypiea"],
["Eris", "F", "Famille Davy", "Civil", "Aucun", "", -1, -1, "Inconnue", "Elbaf"],
["Eustass Kid", "M", "L'Équipage de Kid", "Pirate", "Paramecia", "AOR", 3000000000, 205, "South Blue", "Sabaody"],
["Fisher Tiger", "M", "Équipage des Pirates du Soleil", "Pirate", "Aucun", "", 230000000, 520, "Ile des Hommes-Poissons", "Amazon Lily"],
["Fossa", "M", "L'Équipage de Barbe Blanche", "Pirate", "Aucun", "", -1, -1, "North Blue", "Marineford"],
["Foxy", "M", "L'Équipage de Foxy", "Pirate", "Paramecia", "", 24000000, 180, "South Blue", "Long Ring Long Land"],
["Franky", "M", "Équipage du Chapeau de Paille", "Pirate", "Aucun", "", 394000000, 240, "South Blue", "Water 7"],
["Frères Decalvan", "M", "L'Équipage de Barbe Blanche", "Pirate", "Aucun", "", -1, -1, "Inconnue", "Amazon Lily"],
["Fujitora", "M", "Marines", "Marine", "Paramecia", "AO", 3000000000, 270, "Grand Line", "Dressrosa"],
["Fukaboshi", "M", "Hommes-poissons", "Civil", "Aucun", "", -1, 604, "Ile des Hommes-Poissons", "Ile des Hommes-Poissons"],
["Fukurokuju", "M", "Pays des Wa", "Samourai", "Aucun", "", -1, 221, "Wano", "Wano"],
["Fukurou", "M", "CP-AIGIS0", "Gouvernement", "Aucun", "AO", -1, 331, "Grand Line", "Enies Lobby"],
["Fullbody", "M", "Marines", "Marine", "Aucun", "", -1, 184, "North Blue", "Baratie"],
["Gaimon", "M", "Île aux Trésors", "Pirate", "Aucun", "", -1, 130, "East Blue", "Village de Syrup"],
["Galdino", "M", "Cross Guild", "Civil", "Paramecia", "", 24000000, 179, "South Blue", "Little Garden"],
["Gan Fall", "M", "Skypiéa", "Civil", "Aucun", "", -1, 180, "Ciel", "Skypiea"],
["Gatz", "M", "Colisée Corrida", "Civil", "Aucun", "", -1, -1, "Inconnue", "Dressrosa"],
["Gecko Moria", "M", "Thriller Bark", "Pirate", "Paramecia", "", 320000000, 692, "West Blue", "Thriller Bark"],
["Gedatsu", "M", "Clan d'Ener", "Civil", "Aucun", "O", -1, 220, "Ciel", "Skypiea"],
["Genzo", "M", "Kokoyashi", "Civil", "Aucun", "", -1, 173, "Inconnue", "Arlong Park"],
["Gerd", "F", "Erbaf", "Civil", "Aucun", "", -1, 1700, "Elbaf", "Whole Cake Island"],
["Gin", "M", "Armada de Don Krieg", "Civil", "Aucun", "", 12000000, 186, "Inconnue", "Baratie"],
["Ginney", "F", "Armée Révolutionnaire", "Revolutionnaire", "Aucun", "", 190000000, 174, "Inconnue", "Egghead"],
["Gladius", "M", "Équipage de Don Quijote", "Pirate", "Paramecia", "", 31000000, 260, "North Blue", "Punk Hazard"],
["Gloriosa", "F", "Kujas", "Pirate", "Aucun", "", -1, -1, "Inconnue", "Amazon Lily"],
["Gol D. Roger", "M", "Équipage des Pirates de Roger", "Pirate", "Aucun", "AOR", 5564800000, 274, "East Blue", "Romance Dawn"],
["Goldberg", "M", "Nouvel Équipage des Géants", "Pirate", "Aucun", "", -1, 2100, "Inconnue", "Whole Cake Island"],
["Guernica", "M", "CP-AIGIS0", "Gouvernement", "Aucun", "AO", -1, 243, "Inconnue", "Dressrosa"],
["Hack", "M", "Armée Révolutionnaire", "Revolutionnaire", "Aucun", "", -1, 280, "Ile des Hommes-Poissons", "Dressrosa"],
["Hajrudin", "M", "Erbaf", "Civil", "Aucun", "", -1, 2200, "Elbaf", "Dressrosa"],
["Hamburg", "M", "L'Équipage de Foxy", "Pirate", "Aucun", "", -1, -1, "Inconnue", "Long Ring Long Land"],
["Hammond", "M", "Nouvel équipage des hommes-poissons", "Pirate", "Aucun", "", -1, -1, "Inconnue", "Ile des Hommes-Poissons"],
["Hannyabal", "M", "Gouvernement Mondial", "Gouvernement", "Aucun", "", -1, 309, "South Blue", "Impel Down"],
["Harald", "M", "Famille Royale d'Erbaf", "Civil", "Aucun", "R", -1, -1, "Inconnue", "Elbaf"],
["Haredas", "M", "Weatheria", "Civil", "Aucun", "", -1, 253, "Ciel", "Amazon Lily"],
["Haruta", "M", "L'Équipage de Barbe Blanche", "Pirate", "Aucun", "", -1, -1, "South Blue", "Marineford"],
["Hatchan", "M", "Takoyaki 8", "Civil", "Aucun", "", 8000000, 220, "Ile des Hommes-Poissons", "Arlong Park"],
["Hattori", "M", "CP-AIGIS0", "Gouvernement", "Aucun", "", -1, 25, "Inconnue", "Water 7"],
["Heat", "M", "Équipage de Kidd", "Pirate", "Aucun", "", -1, -1, "South Blue", "Sabaody"],
["Helmeppo", "M", "Marines", "Marine", "Aucun", "O", 100000000, 179, "Inconnue", "Romance Dawn"],
["Higuma", "M", "Bandits des Montagnes", "Civil", "Aucun", "", 8000000, 190, "East Blue", "Romance Dawn"],
["Hina", "F", "Marines", "Marine", "Paramecia", "", -1, 181, "West Blue", "Alabasta"],
["Hody Jones", "M", "Nouvel équipage des hommes-poissons", "Pirate", "Aucun", "", -1, 331, "Ile des Hommes-Poissons", "Ile des Hommes-Poissons"],
["Hogback", "M", "Gecko Moria", "Civil", "Aucun", "", -1, 233, "West Blue", "Thriller Bark"],
["Holdem", "M", "Équipage des cent bêtes", "Pirate", "Aucun", "", -1, 312, "Wano", "Wano"],
["Hyogoro", "M", "Famille Hyogoro", "Civil", "Aucun", "AO", -1, 100, "Inconnue", "Wano"],
["Hyouzou", "M", "Nouvel équipage des hommes-poissons", "Pirate", "Aucun", "", -1, 327, "Ile des Hommes-Poissons", "Ile des Hommes-Poissons"],
["Héraclès", "M", "Archipel de Boing", "Civil", "Aucun", "", -1, 214, "South Blue", "Amazon Lily"],
["Icaros Mucchi", "M", "Nouvel équipage des hommes-poissons", "Pirate", "Aucun", "", -1, 499, "Ile des Hommes-Poissons", "Ile des Hommes-Poissons"],
["Icebarg", "M", "Water Seven", "Civil", "Aucun", "", -1, 199, "Inconnue", "Water 7"],
["Ideo", "M", "Équipage d'Ideo", "Pirate", "Aucun", "", -1, 225, "Grand Line", "Dressrosa"],
["Igaram", "M", "Alabasta", "Civil", "Aucun", "", -1, 218, "Inconnue", "Whisky Peak"],
["Im", "?", "Gouvernement Mondial", "Gouvernement", "Aucun", "OR", -1, -1, "Inconnue", "Reverie"],
["Inazuma", "?", "Révolutionnaires", "Revolutionnaire", "Paramecia", "", 100000000, 228, "South Blue", "Impel Down"],
["Inuarashi", "M", "Principauté de Mokomo", "Civil", "Aucun", "AO", -1, 511, "Grand Line", "Zou"],
["Ippon Matsu", "M", "Loguetown", "Civil", "Aucun", "", -1, 157, "East Blue", "Loguetown"],
["Izo", "M", "L'Équipage de Barbe Blanche", "Pirate", "Aucun", "AO", 510000000, 192, "Wano", "Marineford"],
["Jabra", "M", "CP-AIGIS0", "Gouvernement", "Zoan", "AO", -1, 212, "North Blue", "Enies Lobby"],
["Jack", "M", "Équipage des cent bêtes", "Pirate", "Zoan Ancestral", "AO", 1000000000, 830, "Grand Line", "Dressrosa"],
["Jaguar D. Saul", "M", "Marines", "Marine", "Aucun", "", -1, 1950, "South Blue", "Enies Lobby"],
["Jango", "M", "Marines", "Marine", "Aucun", "", 9000000, 207, "Inconnue", "Village de Syrup"],
["Jarl", "M", "L'Équipage des Géants", "Pirate", "Aucun", "", -1, 2050, "Elbaf", "Whole Cake Island"],
["Jean Bart", "M", "Équipage du Heart", "Pirate", "Aucun", "", 100000000, -1, "Inconnue", "Sabaody"],
["Jesus Burgess", "M", "Équipage de Barbe Noire", "Pirate", "Paramecia", "A", 20000000, 355, "Grand Line", "Jaya"],
["Jewelry Bonney", "F", "L'Équipage de Bonney", "Pirate", "Paramecia", "", 320000000, 174, "South Blue", "Sabaody"],
["Jinbe", "M", "Équipage du Chapeau de Paille", "Pirate", "Aucun", "AO", 1100000000, 301, "Ile des Hommes-Poissons", "Impel Down"],
["John Giant", "M", "Marines", "Marine", "Aucun", "", -1, -1, "Inconnue", "Loguetown"],
["Johnny", "M", "Yosaku", "Civil", "Aucun", "", -1, 186, "East Blue", "Baratie"],
["Jora", "F", "Équipage de Don Quijote", "Pirate", "Paramecia", "", -1, 221, "North Blue", "Punk Hazard"],
["Jozu", "M", "L'Équipage de Barbe Blanche", "Pirate", "Paramecia", "AO", -1, 503, "West Blue", "Jaya"],
["Kabu", "M", "Royaume de Tontatta", "Civil", "Zoan", "", -1, -1, "Inconnue", "Dressrosa"],
["Kaido", "M", "L'Équipage aux Cent Bêtes", "Pirate", "Zoan Mythique", "AOR", 4611100000, 710, "Grand Line", "Dressrosa"],
["Kaku", "M", "CP-AIGIS0", "Gouvernement", "Zoan", "AO", -1, 193, "East Blue", "Water 7"],
["Kalgara", "M", "Shandia", "Civil", "Aucun", "O", -1, 222, "Grand Line", "Skypiea"],
["Kalifa", "F", "CP-AIGIS0", "Gouvernement", "Paramecia", "AO", -1, 185, "Grand Line", "Water 7"],
["Kamakiri", "M", "Shandia", "Civil", "Aucun", "", -1, 214, "Ciel", "Skypiea"],
["Kanjuro", "M", "Famille Kurozumi", "Civil", "Paramecia", "AO", -1, 347, "Wano", "Dressrosa"],
["Karasu", "M", "Révolutionnaires", "Revolutionnaire", "Logia", "AO", 400000000, 265, "North Blue", "Après-guerre"],
["Karin", "F", "École du Morse", "Civil", "Aucun", "", -1, -1, "Inconnue", "Elbaf"],
["Karoo", "M", "Alabasta", "Civil", "Aucun", "", -1, 150, "Inconnue", "Whisky Peak"],
["Kawamatsu", "M", "Famille Kozuki", "Samourai", "Aucun", "AO", -1, 271, "Wano", "Wano"],
["Kaya", "F", "Village de Sirop", "Civil", "Aucun", "", -1, 169, "Inconnue", "Village de Syrup"],
["Kelly Funk", "M", "Colisée Corrida", "Civil", "Paramecia", "", 57000000, 168, "Inconnue", "Dressrosa"],
["Kikyo", "F", "Amazon Lily", "Civil", "Aucun", "", -1, -1, "Calm Belt", "Amazon Lily"],
["Killer", "M", "Équipage de Kidd", "Pirate", "Aucun", "A", 200000000, 195, "South Blue", "Sabaody"],
["Kin'emon", "M", "Famille Kozuki", "Samourai", "Paramecia", "AO", -1, 295, "Wano", "Punk Hazard"],
["King", "M", "Équipage des cent bêtes", "Pirate", "Zoan Ancestral", "AO", 1390000000, 613, "Grand Line", "Wano"],
["King Baum", "M", "Forêt de la Tentation", "Civil", "Aucun", "", -1, 2340, "Inconnue", "Whole Cake Island"],
["Kizaru", "M", "Marines", "Marine", "Logia", "AO", 3000000000, 302, "North Blue", "Sabaody"],
["Koala", "F", "Équipage des Pirates du Soleil", "Pirate", "Aucun", "", -1, 160, "Inconnue", "Ile des Hommes-Poissons"],
["Koby", "M", "Marines", "Marine", "Aucun", "AO", 500000000, 167, "East Blue", "Romance Dawn"],
["Kokoro", "F", "Tom's Workers", "Civil", "Aucun", "", -1, 168, "Ile des Hommes-Poissons", "Water 7"],
["Komachiyo", "M", "Famille Kozuki", "Samourai", "Aucun", "", -1, -1, "Inconnue", "Wano"],
["Kong", "M", "Gouvernement Mondial", "Gouvernement", "Aucun", "", -1, -1, "Inconnue", "Après-guerre"],
["Koza", "M", "Alabasta", "Civil", "Aucun", "", -1, 177, "Inconnue", "Alabasta"],
["Kozuki Hiyori", "F", "Famille Kozuki", "Samourai", "Aucun", "", -1, 170, "Grand Line", "Wano"],
["Kozuki Momonosuke", "M", "Famille Kozuki", "Samourai", "Zoan Mythique", "", -1, 322, "Grand Line", "Punk Hazard"],
["Kozuki Oden", "M", "Famille Kozuki", "Samourai", "Aucun", "AOR", -1, 382, "Wano", "Wano"],
["Kozuki Sukiyaki", "M", "Famille Kozuki", "Samourai", "Aucun", "", -1, 214, "Inconnue", "Wano"],
["Kozuki Toki", "F", "Famille Kozuki", "Samourai", "Paramecia", "", -1, 190, "Inconnue", "Wano"],
["Kumadori", "M", "CP-AIGIS0", "Gouvernement", "Aucun", "AO", -1, 318, "South Blue", "Enies Lobby"],
["Kuro", "M", "Équipage du Chat Noir", "Pirate", "Aucun", "", 16000000, 207, "Inconnue", "Village de Syrup"],
["Kuromarimo", "M", "Équipage du Bliking", "Pirate", "Aucun", "", -1, 186, "Inconnue", "Drum"],
["Kuroobi", "M", "Équipage d'Arlong", "Pirate", "Aucun", "", 9000000, 252, "Ile des Hommes-Poissons", "Arlong Park"],
["Kurozumi Higurashi", "F", "Pays des Wa", "Samourai", "Paramecia", "", -1, 193, "Inconnue", "Wano"],
["Kurozumi Orochi", "M", "Équipage des cent bêtes", "Pirate", "Zoan Mythique", "", -1, 350, "Wano", "Wano"],
["Kyros", "M", "Colisée Corrida", "Civil", "Aucun", "", -1, 298, "Inconnue", "Dressrosa"],
["Laboon", "M", "Crocus", "Civil", "Aucun", "", -1, 40000, "West Blue", "Reverse Mountain"],
["Lacroix", "M", "Marines", "Marine", "Aucun", "", -1, -1, "Inconnue", "Marineford"],
["Lafitte", "M", "Équipage de Barbe Noire", "Pirate", "Aucun", "", 42200000, 340, "West Blue", "Jaya"],
["Laki", "F", "Shandia", "Civil", "Aucun", "", -1, 179, "Ciel", "Skypiea"],
["Lao G", "M", "Équipage de Don Quijote", "Pirate", "Aucun", "", 61000000, 157, "North Blue", "Punk Hazard"],
["Lassou", "M", "Baroque Works", "Pirate", "Zoan", "", -1, -1, "Inconnue", "Alabasta"],
["Leo", "M", "Équipage des Tontatta", "Pirate", "Paramecia", "", -1, 23, "Inconnue", "Dressrosa"],
["Lilith", "F", "Gouvernement Mondial", "Gouvernement", "Aucun", "", -1, 204, "Inconnue", "Egghead"],
["Lindbergh", "M", "Révolutionnaires", "Revolutionnaire", "Aucun", "AO", 316000000, 149, "Inconnue", "Reverie"],
["Little Oars Jr.", "M", "L'Équipage de Barbe Blanche", "Pirate", "Aucun", "", 550000000, 6000, "Grand Line", "Marineford"],
["Loki", "M", "Famille Royale d'Erbaf", "Pirate", "Zoan Mythique", "", 2600000000, -1, "Inconnue", "Elbaf"],
["Lucky Roo", "M", "L'Équipage du Roux", "Pirate", "Aucun", "AO", -1, 241, "South Blue", "Romance Dawn"],
["Lulu", "M", "Galley-La Company", "Civil", "Aucun", "", -1, 206, "Inconnue", "Water 7"],
["Machvise", "M", "Équipage de Don Quijote", "Pirate", "Paramecia", "", 11000000, 440, "North Blue", "Punk Hazard"],
["Magellan", "M", "Gouvernement Mondial", "Gouvernement", "Paramecia", "", -1, 491, "Grand Line", "Impel Down"],
["Magra", "M", "Famille Dadan", "Civil", "Aucun", "", -1, -1, "East Blue", "Après-guerre"],
["Makino", "F", "Village de Fuchsia", "Civil", "Aucun", "", -1, 166, "East Blue", "Romance Dawn"],
["Manboshi", "M", "Île des Hommes-Poissons", "Civil", "Aucun", "", -1, 473, "Ile des Hommes-Poissons", "Ile des Hommes-Poissons"],
["Mansherry", "F", "Royaume de Tontatta", "Civil", "Paramecia", "", -1, 20, "Inconnue", "Dressrosa"],
["Marco", "M", "L'Équipage de Barbe Blanche", "Pirate", "Zoan Mythique", "AO", 1374000000, 203, "Grand Line", "Jaya"],
["Marguerite", "F", "Kujas", "Pirate", "Aucun", "A", -1, 178, "Calm Belt", "Amazon Lily"],
["Masira", "M", "Forces Spéciales Simiesques", "Civil", "Aucun", "", 23000000, 345, "North Blue", "Jaya"],
["McKinley", "M", "Skypiéa", "Civil", "Aucun", "", -1, -1, "Inconnue", "Skypiea"],
["Merry", "M", "Sirop", "Civil", "Aucun", "", -1, -1, "Inconnue", "Village de Syrup"],
["Minotaure", "M", "Impel Down", "Gouvernement", "Aucun", "", -1, -1, "Inconnue", "Impel Down"],
["Miss Doublefinger", "F", "Spider's Café", "Civil", "Paramecia", "", 35000000, 187, "Grand Line", "Alabasta"],
["Miss Goldenweek", "F", "Spider's Café", "Civil", "Aucun", "", 29000000, 145, "North Blue", "Little Garden"],
["Miss Monday", "F", "Baroque Works", "Pirate", "Aucun", "", -1, -1, "Grand Line", "Whisky Peak"],
["Miss Valentine", "F", "Spider's Café", "Civil", "Paramecia", "", 7500000, 177, "West Blue", "Whisky Peak"],
["Miyagi", "M", "Principauté de Mokomo", "Civil", "Aucun", "", -1, -1, "Inconnue", "Zou"],
["Mocha", "F", "Enfants de Punk Hazard", "Civil", "Aucun", "", -1, 692, "Grand Line", "Punk Hazard"],
["Momonga", "M", "Marines", "Marine", "Aucun", "AO", -1, 251, "Grand Line", "Enies Lobby"],
["Monet", "F", "César Clown", "Civil", "Logia", "", -1, 227, "North Blue", "Punk Hazard"],
["Monkey D. Dragon", "M", "Armée de la Liberté", "Revolutionnaire", "Aucun", "", -1, 256, "East Blue", "Loguetown"],
["Monkey D. Garp", "M", "Marines", "Marine", "Aucun", "AOR", 3000000000, 287, "East Blue", "Arlong Park"],
["Monkey D. Luffy", "M", "Équipage du Chapeau de Paille", "Pirate", "Zoan Mythique", "AOR", 3000000000, 174, "East Blue", "Romance Dawn"],
["Mont Blanc Cricket", "M", "Ligue des Primates", "Civil", "Aucun", "", 25000000, 242, "North Blue", "Jaya"],
["Mont Blanc Noland", "M", "Royaume de Luvneel", "Civil", "Aucun", "", -1, 220, "North Blue", "Skypiea"],
["Morgan", "M", "Marines", "Marine", "Aucun", "", -1, 285, "Inconnue", "Romance Dawn"],
["Morgans", "M", "World Economy News Paper", "Civil", "Zoan", "", -1, 305, "Grand Line", "Whole Cake Island"],
["Morley", "?", "Révolutionnaires", "Revolutionnaire", "Paramecia", "AO", 293000000, 1253, "Inconnue", "Reverie"],
["Mozu et Kiwi", "F", "Franky Family", "Civil", "Aucun", "", -1, 187, "Grand Line", "Water 7"],
["Mr 9", "M", "Baroque Works", "Pirate", "Aucun", "", -1, -1, "Grand Line", "Reverse Mountain"],
["Mr. 2 Bon Clay", "?", "Baroque Works", "Pirate", "Paramecia", "", 32000000, 238, "East Blue", "Little Garden"],
["Mr. 5", "M", "Baroque Works", "Pirate", "Paramecia", "", 10000000, 197, "South Blue", "Whisky Peak"],
["Nami", "F", "Équipage du Chapeau de Paille", "Pirate", "Aucun", "", 366000000, 170, "East Blue", "Ville d'Orange"],
["Nefeltari Cobra", "M", "Famille Nefertari", "Civil", "Aucun", "", -1, 182, "Inconnue", "Drum"],
["Nefeltari Vivi", "F", "Alabasta", "Civil", "Aucun", "", -1, 169, "Inconnue", "Reverse Mountain"],
["Nefertari D. Lillie", "F", "Alabasta", "Civil", "Aucun", "", -1, -1, "Inconnue", "Egghead"],
["Nekomamushi", "M", "Principauté de Mokomo", "Civil", "Aucun", "AO", -1, 522, "Grand Line", "Zou"],
["Neptune", "M", "royaume Ryugu", "Civil", "Aucun", "", -1, 1220, "Ile des Hommes-Poissons", "Ile des Hommes-Poissons"],
["Nero", "M", "CP9", "Civil", "Aucun", "", -1, 202, "West Blue", "Water 7"],
["Nezumi", "M", "Marines", "Marine", "Aucun", "", -1, 182, "East Blue", "Arlong Park"],
["Nico Olvia", "F", "Ohara", "Civil", "Aucun", "", 79000000, 186, "West Blue", "Enies Lobby"],
["Nico Robin", "F", "Équipage du Chapeau de Paille", "Pirate", "Paramecia", "", 930000000, 188, "West Blue", "Whisky Peak"],
["Nojiko", "F", "Village de Cocoyashi", "Civil", "Aucun", "", -1, 170, "East Blue", "Arlong Park"],
["Oars", "M", "Thriller Bark", "Pirate", "Aucun", "", -1, 6700, "North Blue", "Thriller Bark"],
["Ohm", "M", "Clan d'Ener", "Civil", "Aucun", "O", -1, 189, "Ciel", "Skypiea"],
["Oignon", "M", "Équipage du Capitaine Usopp", "Pirate", "Aucun", "", -1, 124, "Inconnue", "Village de Syrup"],
["Oimo", "M", "L'Équipage des Géants", "Pirate", "Aucun", "", -1, 1600, "Elbaf", "Enies Lobby"],
["Onigumo", "M", "Marines", "Marine", "Zoan", "", -1, -1, "Inconnue", "Enies Lobby"],
["Onimaru", "M", "Famille Shimotsuki", "Civil", "Zoan Mythique", "", -1, 428, "Inconnue", "Wano"],
["Orlumbus", "M", "Yonta Maria", "Civil", "Aucun", "", 148000000, 480, "Grand Line", "Dressrosa"],
["Otohime", "F", "Île des Hommes-Poissons", "Civil", "Aucun", "O", -1, 224, "Ile des Hommes-Poissons", "Ile des Hommes-Poissons"],
["Page One", "M", "Équipage des cent bêtes", "Pirate", "Zoan Ancestral", "", 290000000, 171, "Grand Line", "Wano"],
["Pandaman", "M", "Équipage de Pandaman; Panda Family", "Pirate", "Aucun", "", 3333333, 200, "Inconnue", "Baratie"],
["Pappag", "M", "Takoyaki 8", "Civil", "Aucun", "", -1, 50, "Inconnue", "Alabasta"],
["Patty", "M", "Baratie", "Civil", "Aucun", "", -1, 204, "Inconnue", "Baratie"],
["Pauly", "M", "Galley-La Company", "Civil", "Aucun", "", -1, 195, "Inconnue", "Water 7"],
["Pearl", "M", "Armada de Don Krieg", "Civil", "Aucun", "", -1, 239, "Inconnue", "Baratie"],
["Pedro", "M", "Zou", "Civil", "Aucun", "AO", 382000000, 233, "Grand Line", "Zou"],
["Pekoms", "M", "Équipage de Big Mom", "Pirate", "Zoan", "AO", 330000000, 232, "Inconnue", "Ile des Hommes-Poissons"],
["Pell", "M", "Alabasta", "Civil", "Zoan", "", -1, 189, "Inconnue", "Alabasta"],
["Penguin", "M", "Équipage du Heart", "Pirate", "Aucun", "", -1, -1, "North Blue", "Sabaody"],
["Perona", "F", "Dracule Mihawk", "Civil", "Paramecia", "", -1, 160, "West Blue", "Thriller Bark"],
["Pica", "M", "Équipage de Don Quijote", "Pirate", "Paramecia", "AO", 99000000, 470, "North Blue", "Dressrosa"],
["Pierre", "M", "Gan Forr", "Civil", "Zoan", "", -1, -1, "Inconnue", "Skypiea"],
["Piment", "M", "Équipage du Capitaine Usopp", "Pirate", "Aucun", "", -1, 120, "Inconnue", "Village de Syrup"],
["Porche", "F", "L'Équipage de Foxy", "Pirate", "Aucun", "", -1, -1, "Inconnue", "Long Ring Long Land"],
["Porchemy", "M", "L'Équipage de Bluejam", "Pirate", "Aucun", "", 3400000, 320, "East Blue", "Après-guerre"],
["Portgas D. Ace", "M", "L'Équipage de Barbe Blanche", "Pirate", "Logia", "AOR", 550000000, 185, "South Blue", "Drum"],
["Pound", "M", "Famille Charlotte", "Pirate", "Aucun", "", -1, 731, "Grand Line", "Whole Cake Island"],
["Pythagoras", "?", "Gouvernement Mondial", "Gouvernement", "Aucun", "", -1, 351, "Inconnue", "Egghead"],
["Queen", "M", "Équipage des cent bêtes", "Pirate", "Zoan Ancestral", "AO", 1320000000, 612, "Grand Line", "Wano"],
["Raizo", "M", "Pays des Wa", "Samourai", "Paramecia", "AO", -1, 311, "Wano", "Zou"],
["Rebecca", "F", "Colisée Corrida", "Civil", "Aucun", "", -1, 171, "Inconnue", "Dressrosa"],
["Richie", "M", "L'Équipage du Clown", "Pirate", "Aucun", "", -1, -1, "Inconnue", "Ville d'Orange"],
["Riku", "M", "Dressrosa", "Civil", "Aucun", "", -1, 261, "Inconnue", "Dressrosa"],
["Ripley", "F", "École du Morse", "Civil", "Aucun", "", -1, -1, "Inconnue", "Elbaf"],
["Rob Lucci", "M", "CP-AIGIS0", "Gouvernement", "Zoan", "AO", -1, 212, "Grand Line", "Water 7"],
["Rocks D. Xebec", "M", "Équipage de Rocks", "Pirate", "Aucun", "R", -1, 435, "West Blue", "Wano"],
["Rockstar", "M", "L'Équipage du Roux", "Pirate", "Aucun", "", 94000000, -1, "Inconnue", "Jaya"],
["Ronja", "F", "École du Morse", "Civil", "Aucun", "", -1, -1, "Inconnue", "Elbaf"],
["Ronse", "M", "Marines", "Marine", "Aucun", "", -1, -1, "Inconnue", "Marineford"],
["Roronoa Zoro", "M", "Équipage du Chapeau de Paille", "Pirate", "Aucun", "AOR", 1111000000, 181, "East Blue", "Romance Dawn"],
["Rouge", "F", "Gol D. Roger", "Civil", "Aucun", "", -1, -1, "Inconnue", "Marineford"],
["Ryokugyu", "M", "Marines", "Marine", "Logia", "AO", 3000000000, 308, "Inconnue", "Dressrosa"],
["Ryuboshi", "M", "Hommes-poissons", "Civil", "Aucun", "", -1, 544, "Ile des Hommes-Poissons", "Ile des Hommes-Poissons"],
["S-Bear", "M", "Seraphim", "Civil", "Paramecia", "AO", -1, 660, "Inconnue", "Egghead"],
["S-Hawk", "M", "Seraphim", "Civil", "Paramecia", "AO", -1, 212, "Inconnue", "Egghead"],
["S-Shark", "M", "Seraphim", "Civil", "Paramecia", "", -1, 320, "Inconnue", "Egghead"],
["S-Snake", "F", "Seraphim", "Civil", "Paramecia", "AO", -1, 208, "Inconnue", "Egghead"],
["Sabo", "M", "Armée Révolutionnaire", "Revolutionnaire", "Logia", "AO", 602000000, 187, "East Blue", "Après-guerre"],
["Sadi", "F", "Impel Down", "Gouvernement", "Aucun", "", -1, 183, "Grand Line", "Impel Down"],
["Sai", "M", "Flotte de Happou", "Civil", "Aucun", "AO", 210000000, 242, "West Blue", "Dressrosa"],
["Saint Charlos", "M", "Gouvernement Mondial", "Gouvernement", "Aucun", "", -1, 230, "Inconnue", "Sabaody"],
["Saint Don Quichotte Mjosgard", "M", "Gouvernement Mondial", "Gouvernement", "Aucun", "", -1, 211, "Inconnue", "Ile des Hommes-Poissons"],
["Saint Ethanbaron V. Nusjuro", "M", "Cinq Doyens", "Civil", "Zoan Mythique", "A", -1, -1, "Inconnue", "Jaya"],
["Saint Figarland Garling", "M", "Cinq Doyens", "Civil", "Aucun", "", -1, -1, "Inconnue", "Egghead"],
["Saint Figarland Shamrock", "M", "Chevaliers Divins", "Civil", "Aucun", "", -1, -1, "West Blue", "Reverie"],
["Saint Jaygarcia Saturn", "M", "Cinq Doyens", "Civil", "Zoan Mythique", "R", -1, -1, "Inconnue", "Jaya"],
["Saint Limoshiv Killingham", "M", "Chevaliers Divins", "Civil", "Zoan Mythique", "", -1, -1, "Inconnue", "Elbaf"],
["Saint Manmayer Glow", "M", "Chevaliers Divins", "Civil", "Aucun", "", -1, -1, "Inconnue", "Elbaf"],
["Saint Marcus Mars", "M", "Cinq Doyens", "Civil", "Zoan Mythique", "", -1, -1, "Inconnue", "Jaya"],
["Saint Rosward Rosward", "M", "Gouvernement Mondial", "Gouvernement", "Aucun", "", -1, 215, "Inconnue", "Sabaody"],
["Saint Shepherd Ju Peter", "M", "Cinq Doyens", "Civil", "Zoan Mythique", "", -1, -1, "Inconnue", "Jaya"],
["Saint Shepherd Sommers", "M", "Chevaliers Divins", "Civil", "Paramecia", "", -1, -1, "Inconnue", "Elbaf"],
["Saint Topman Warcury", "M", "Cinq Doyens", "Civil", "Zoan Mythique", "", -1, -1, "Inconnue", "Jaya"],
["Sainte Manmayer Gunko", "F", "Chevaliers Divins", "Civil", "Paramecia", "", -1, -1, "Inconnue", "Elbaf"],
["Sainte Rosward Sharlia", "F", "Gouvernement Mondial", "Gouvernement", "Aucun", "", -1, 178, "Inconnue", "Sabaody"],
["Sainte Satchels Maffey", "F", "Chevaliers Divins", "Civil", "Aucun", "", -1, -1, "Inconnue", "Elbaf"],
["Saldeath", "M", "Impel Down", "Gouvernement", "Aucun", "", -1, 218, "Grand Line", "Impel Down"],
["Sanji", "M", "Équipage du Chapeau de Paille", "Pirate", "Aucun", "AO", 1032000000, 180, "Inconnue", "Baratie"],
["Sanjuan Wolf", "M", "Équipage de Barbe Noire", "Pirate", "Paramecia", "", 100000000, 18000, "West Blue", "Marineford"],
["Sarquiss", "M", "Équipage de Bellamy", "Pirate", "Aucun", "", 38000000, 228, "Inconnue", "Jaya"],
["Sasaki", "M", "Équipage des cent bêtes", "Pirate", "Zoan Ancestral", "AO", 472000000, 318, "Grand Line", "Wano"],
["Satori", "M", "Clan d'Ener", "Civil", "Aucun", "", -1, 179, "Ciel", "Skypiea"],
["Scarlett", "F", "Dressrosa", "Civil", "Aucun", "", -1, -1, "Inconnue", "Dressrosa"],
["Scopper Gaban", "M", "L'Équipage des Pirates Roger", "Pirate", "Aucun", "", -1, -1, "Inconnue", "Ville d'Orange"],
["Scratchmen Apoo", "M", "Équipage du On-Air", "Pirate", "Paramecia", "AO", 198000000, 256, "Grand Line", "Sabaody"],
["Sengoku", "M", "Marines", "Marine", "Zoan Mythique", "AOR", -1, 278, "South Blue", "Jaya"],
["Senor Pink", "M", "Équipage de Don Quijote", "Pirate", "Paramecia", "", 58000000, 244, "North Blue", "Dressrosa"],
["Sentomaru", "M", "Vegapunk", "Civil", "Aucun", "AO", 500000000, 279, "Grand Line", "Sabaody"],
["Shaka", "M", "Gouvernement Mondial", "Gouvernement", "Aucun", "", -1, 220, "Inconnue", "Egghead"],
["Shakky", "F", "Rip-Off Bar de Shakky", "Civil", "Aucun", "", -1, 186, "Calm Belt", "Sabaody"],
["Sham", "M", "Équipage du Chat Noir", "Pirate", "Aucun", "", 7000000, 201, "East Blue", "Village de Syrup"],
["Shanks", "M", "L'Équipage du Roux", "Pirate", "Aucun", "AOR", 4048900000, 199, "West Blue", "Romance Dawn"],
["Shiki", "M", "L'Équipage du Lion d'Or", "Pirate", "Paramecia", "", -1, -1, "Inconnue", "Impel Down"],
["Shimotsuki Kozaburo", "M", "Pays des Wa", "Samourai", "Aucun", "", -1, 221, "Inconnue", "Wano"],
["Shimotsuki Kuina", "F", "Famille Shimotsuki", "Civil", "Aucun", "", -1, 150, "Inconnue", "Romance Dawn"],
["Shimotsuki Kôshirô", "M", "Famille Shimotsuki", "Civil", "Aucun", "", -1, 184, "East Blue", "Romance Dawn"],
["Shimotsuki Ryuma", "M", "Famille Shimotsuki", "Samourai", "Aucun", "A", -1, 179, "Wano", "Thriller Bark"],
["Shimotsuki Ushimaru", "M", "Famille Shimotsuki", "Civil", "Aucun", "AO", -1, 298, "Inconnue", "Wano"],
["Shimotsuki Yasuie", "M", "Pays des Wa", "Samourai", "Aucun", "", -1, 155, "Inconnue", "Wano"],
["Shinobu", "F", "Famille Kozuki", "Samourai", "Paramecia", "", -1, 180, "Wano", "Wano"],
["Shirahoshi", "F", "Neptune", "Civil", "Aucun", "", -1, 1187, "Ile des Hommes-Poissons", "Ile des Hommes-Poissons"],
["Shiryu", "M", "Équipage de Barbe Noire", "Pirate", "Paramecia", "AO", -1, 340, "Grand Line", "Impel Down"],
["Shishilian", "M", "Principauté de Mokomo", "Civil", "Aucun", "", -1, 196, "Grand Line", "Zou"],
["Shojo", "M", "Ligue des Primates", "Civil", "Aucun", "", 36000000, 351, "South Blue", "Jaya"],
["Shura", "M", "Clan d'Ener", "Civil", "Aucun", "O", -1, 220, "Ciel", "Skypiea"],
["Shyarly", "F", "Mermaid Café", "Civil", "Aucun", "", -1, 520, "Ile des Hommes-Poissons", "Ile des Hommes-Poissons"],
["Silvers Rayleigh", "M", "Équipage des Pirates de Roger", "Pirate", "Aucun", "AOR", -1, 188, "Inconnue", "Ville d'Orange"],
["Smack", "M", "L’Équipage de Wapol", "Pirate", "Aucun", "", -1, 194, "Inconnue", "Drum"],
["Smiley", "M", "César Clown", "Civil", "Zoan", "", -1, 15000, "Inconnue", "Punk Hazard"],
["Smoker", "M", "Marines", "Marine", "Logia", "AO", -1, 209, "Grand Line", "Loguetown"],
["Spandam", "M", "CP-AIGIS0", "Gouvernement", "Aucun", "", -1, 192, "Grand Line", "Water 7"],
["Spandine", "M", "CP9", "Civil", "Aucun", "", -1, 275, "Grand Line", "Enies Lobby"],
["Speed", "F", "L'Équipage aux Cent Bêtes", "Pirate", "Aucun", "", -1, 298, "Wano", "Wano"],
["Squardo", "M", "L'Équipage de Barbe Blanche", "Pirate", "Aucun", "", 210000000, 228, "Grand Line", "Marineford"],
["Stansen", "M", "Nouvel Équipage des Géants", "Pirate", "Aucun", "", -1, 1950, "Inconnue", "Sabaody"],
["Stelly", "M", "Royaume de Goa", "Civil", "Aucun", "", -1, 180, "Inconnue", "Après-guerre"],
["Strawberry", "M", "Marines", "Marine", "Aucun", "", -1, -1, "Inconnue", "Enies Lobby"],
["Streusen", "M", "Équipage de Big Mom", "Pirate", "Paramecia", "", -1, 140, "Grand Line", "Whole Cake Island"],
["Stussy", "F", "CP-AIGIS0", "Gouvernement", "Zoan", "AO", -1, 179, "Grand Line", "Whole Cake Island"],
["Sugar", "F", "Équipage de Don Quijote", "Pirate", "Paramecia", "", -1, 110, "North Blue", "Punk Hazard"],
["Suleiman", "M", "Équipage des Jolis Pirates", "Pirate", "Aucun", "", 67000000, 240, "South Blue", "Dressrosa"],
["Surume", "M", "L'Équipage des Nouveaux Hommes-Poissons", "Pirate", "Aucun", "", -1, 30000, "North Blue", "Ile des Hommes-Poissons"],
["T-Bone", "M", "Marines", "Marine", "Aucun", "", -1, 200, "Grand Line", "Water 7"],
["Tama", "F", "Pays des Wa", "Samourai", "Paramecia", "", -1, 108, "Inconnue", "Wano"],
["Tamago", "M", "Équipage de Big Mom", "Pirate", "Zoan", "AO", 429000000, 301, "Grand Line", "Ile des Hommes-Poissons"],
["Tanaka", "M", "Gran Tesoro", "Civil", "Paramecia", "", -1, -1, "Inconnue", "Whole Cake Island"],
["Tashigi", "F", "Marines", "Marine", "Aucun", "", -1, 170, "East Blue", "Loguetown"],
["Thatch", "M", "L'Équipage de Barbe Blanche", "Pirate", "Aucun", "", -1, -1, "North Blue", "Post-Enies Lobby"],
["Tilestone", "M", "Galley-La Company", "Civil", "Aucun", "", -1, 255, "Inconnue", "Water 7"],
["Toko", "F", "Pays des Wa", "Samourai", "Aucun", "", -1, 89, "Inconnue", "Wano"],
["Tom", "M", "Tom's Workers", "Civil", "Aucun", "", -1, 296, "Ile des Hommes-Poissons", "Water 7"],
["Tony Tony Chopper", "M", "Équipage du Chapeau de Paille", "Pirate", "Zoan", "", 1000, -1, "Grand Line", "Drum"],
["Toto", "M", "Alabasta", "Civil", "Aucun", "", -1, -1, "Inconnue", "Alabasta"],
["Trafalgar D. Water Law", "M", "Équipage du Heart", "Pirate", "Paramecia", "AO", 3000000000, 191, "North Blue", "Sabaody"],
["Trebol", "M", "Équipage de Don Quijote", "Pirate", "Paramecia", "AO", 99000000, 349, "North Blue", "Dressrosa"],
["Ulti", "F", "Équipage des cent bêtes", "Pirate", "Zoan Ancestral", "A", 400000000, 173, "Grand Line", "Wano"],
["Urouge", "M", "Équipage des moines dépravés", "Pirate", "Paramecia", "", 108000000, 388, "Ciel", "Sabaody"],
["Usopp", "M", "Équipage du Chapeau de Paille", "Pirate", "Aucun", "O", 500000000, 176, "Inconnue", "Village de Syrup"],
["Van Augur", "M", "Équipage de Barbe Noire", "Pirate", "Paramecia", "", 64000000, 340, "East Blue", "Jaya"],
["Vander Decken IX", "M", "L'Équipage des Pirates Volants", "Pirate", "Paramecia", "", -1, 352, "Ile des Hommes-Poissons", "Ile des Hommes-Poissons"],
["Vasco Shot", "M", "Équipage de Barbe Noire", "Pirate", "Paramecia", "", 100000000, 573, "South Blue", "Marineford"],
["Vegapunk", "M", "Gouvernement Mondial", "Gouvernement", "Paramecia", "", -1, 314, "Grand Line", "Egghead"],
["Vergo", "M", "Marines", "Marine", "Aucun", "A", -1, 247, "North Blue", "Punk Hazard"],
["Victoria Cindry", "F", "Hogback", "Civil", "Aucun", "", -1, 188, "West Blue", "Thriller Bark"],
["Vinsmoke Ichiji", "M", "Germa 66", "Civil", "Aucun", "", -1, 186, "North Blue", "Whole Cake Island"],
["Vinsmoke Judge", "M", "Royaume de Germa", "Civil", "Aucun", "", -1, 272, "North Blue", "Whole Cake Island"],
["Vinsmoke Niji", "M", "Germa 66", "Civil", "Aucun", "", -1, 185, "North Blue", "Whole Cake Island"],
["Vinsmoke Reiju", "F", "Germa 66", "Civil", "Aucun", "", -1, 173, "North Blue", "Whole Cake Island"],
["Vinsmoke Sora", "F", "Germa 66", "Civil", "Aucun", "", -1, -1, "Inconnue", "Whole Cake Island"],
["Vinsmoke Yonji", "M", "Germa 66", "Civil", "Aucun", "", -1, 194, "North Blue", "Whole Cake Island"],
["Viola", "F", "Équipage de Don Quijote", "Pirate", "Paramecia", "", -1, 178, "Inconnue", "Dressrosa"],
["Vista", "M", "L'Équipage de Barbe Blanche", "Pirate", "Aucun", "AO", -1, 328, "North Blue", "Marineford"],
["Vito", "M", "Équipage du Fire Tank", "Pirate", "Aucun", "", 95000000, 242, "West Blue", "Zou"],
["Wadatsumi", "M", "Équipage des Pirates du Soleil", "Pirate", "Aucun", "", -1, 8000, "Ile des Hommes-Poissons", "Ile des Hommes-Poissons"],
["Wanda", "F", "Principauté de Mokomo", "Civil", "Aucun", "", -1, 181, "Grand Line", "Zou"],
["Wanze", "M", "CP7", "Civil", "Aucun", "", -1, 173, "West Blue", "Water 7"],
["Wapol", "M", "Royaume maléfique de Black Drum", "Civil", "Paramecia", "", -1, 207, "Inconnue", "Drum"],
["Who's-Who", "M", "Équipage des cent bêtes", "Pirate", "Zoan Ancestral", "AO", 546000000, 336, "North Blue", "Wano"],
["Wiper", "M", "Shandia", "Civil", "Aucun", "", -1, 183, "Ciel", "Skypiea"],
["X Drake", "M", "Équipage de Drake", "Pirate", "Zoan Ancestral", "AO", 222000000, 233, "North Blue", "Sabaody"],
["Yamato", "?", "Alliance des Ninjas-Pirates-Minks-Samouraï", "Samourai", "Zoan Mythique", "AOR", -1, 263, "Inconnue", "Wano"],
["Yasopp", "M", "L'Équipage du Roux", "Pirate", "Aucun", "AO", -1, 183, "East Blue", "Romance Dawn"],
["Yeti Cool Brothers", "M", "César Clown", "Civil", "Aucun", "", 20000000, 4250, "Grand Line", "Punk Hazard"],
["Yokozuna", "M", "Tom's Workers", "Civil", "Aucun", "", -1, -1, "Inconnue", "Water 7"],
["York", "F", "Gouvernement Mondial", "Gouvernement", "Aucun", "", -1, 482, "Inconnue", "Egghead"],
["Yorki", "M", "L'Équipage des Pirates Rumbar", "Pirate", "Aucun", "", -1, -1, "Inconnue", "Reverse Mountain"],
["Yosaku", "M", "Johnny", "Civil", "Aucun", "", -1, 185, "East Blue", "Baratie"],
["Zambai", "M", "Franky Family", "Civil", "Aucun", "", -1, 237, "Inconnue", "Water 7"],
["Zeff", "M", "Baratie", "Civil", "Aucun", "", 60000000, 189, "East Blue", "Baratie"],
["Zeo", "M", "Nouvel équipage des hommes-poissons", "Pirate", "Aucun", "", -1, 325, "Ile des Hommes-Poissons", "Ile des Hommes-Poissons"]
];
