/* ============================================================
   Indices emoji — couche écrite à la main, alimentant le mode Emoji.
   Volontairement séparée de characters.js, qui est régénérable
   depuis le wiki : régénérer le dataset ne détruit plus ce fichier.
   Ajouter une entrée suffit à faire entrer le personnage dans le mode.
   ============================================================ */
const EMOJI = {
"Monkey D. Luffy":"👒🥩🖐️","Roronoa Zoro":"⚔️🗺️🍶","Nami":"🍊🗺️⛈️","Usopp":"🤥🎯🌱",
"Sanji":"🦵🚬🍳","Tony Tony Chopper":"🦌🎩💊","Nico Robin":"🌸🖐️📜","Franky":"🤖🥤💪",
"Brook":"💀🎻🎩","Jinbe":"🦈🥋🌊","Gol D. Roger":"👑🏴‍☠️💎","Barbe Blanche":"🌊🔱👨‍👦",
"Kaido":"🐉🍶🔨","Big Mom":"🍰👵⛈️","Shanks":"🦰🗡️👒","Barbe Noire":"🌑🦷😈",
"Silvers Rayleigh":"🕶️🍺⚔️","Scopper Gaban":"🪓🏴‍☠️","Crocus":"🐋🩺","Buggy":"🤡🔪🎪",
"Shiki":"🦁🛞","Portgas D. Ace":"🔥🎩🃏","Marco":"🔵🐦‍🔥🩺","Jozu":"💎🛡️","Vista":"🌹⚔️",
"Izo":"🔫💄","Thatch":"🍳🏴‍☠️","Squardo":"🦈⚔️","Edward Weevil":"🌙👶",
"Charlotte Katakuri":"🍩🔱🧣","Charlotte Cracker":"🍪🗡️","Charlotte Smoothie":"🧃🍹",
"Charlotte Perospero":"🍭👅","Charlotte Oven":"🔥🍳","Charlotte Daifuku":"🧞‍♂️🫘",
"Charlotte Brulee":"🪞😈","Charlotte Pudding":"👁️🍮🔫","Charlotte Chiffon":"🎂👶",
"Charlotte Praline":"🦈👰","Pound":"🪵😭","Streusen":"👨‍🍳🔪","King":"🦖🔥🖤",
"Queen":"🦕🕺🧪","Jack":"🐘🌊","Yamato":"🐺⛓️📖","Ulti":"🦖👊","Page One":"🦖🕶️",
"Who's-Who":"🐆🗡️","Black Maria":"🕷️🎎","Sasaki":"🐢🌀","Kanjuro":"🖌️🎭",
"Kurozumi Orochi":"🐍🍶👑","Babanuki":"🐘🏴‍☠️","Shiryu":"🌫️⚔️",
"Jesus Burgess":"🤼💪","Van Augur":"🔭🔫","Lafitte":"🎩🕊️","Doc Q":"🤒🍎",
"Catarina Devon":"🦊🌙","Avalo Pizarro":"🏝️👑","Vasco Shot":"🍶🥴","Sanjuan Wolf":"🚢🧌",
"Benn Beckman":"🚬🔫🧠","Lucky Roo":"🍖🔫","Yasopp":"🎯🔫","Rockstar":"🎸🏴‍☠️",
"Dracule Mihawk":"🦅⚔️🍷","Crocodile":"🐊🪝🚬","Donquixote Doflamingo":"🧵🕶️🦩",
"Boa Hancock":"🐍💗👑","Gecko Moria":"👻✂️🦇","Bartholomew Kuma":"🐻📖🍑",
"Arlong":"🦈👃","Hatchan":"🐙🍜","Kuroobi":"🐟🥋","Chew":"🐡💦","Kuro":"🐈‍⬛🤓🐾",
"Don Krieg":"💣🛡️","Gin":"🍚🔨","Alvida":"🔨💅","Foxy":"🦊🐌","Bellamy":"🌀😈",
"Wapol":"🥫👑","Caribou":"🌾😇","Hody Jones":"🦈💊","Vander Decken IX":"🎯💌",
"Daz Bones":"🔪1️⃣","Miss Doublefinger":"🌵💃","Mr. 2 Bon Clay":"🦢🩰2️⃣","Galdino":"🕯️3️⃣",
"Miss Goldenweek":"🎨🍡","Mr. 5":"💥👃","Miss Valentine":"☂️⚖️","Monkey D. Garp":"👊🍩⚓",
"Sengoku":"🗿🍘⚖️","Akainu":"🌋🔥🧢","Aokiji":"❄️😴🚲","Kizaru":"💡🕶️🍡",
"Fujitora":"🌌🦯⚖️","Ryokugyu":"🌳🍽️","Smoker":"🚬💨🐆","Tashigi":"👓⚔️","Koby":"🌸👊",
"Helmeppo":"💇🗡️","Hina":"⛓️🚬","Vergo":"🎋🕶️","Sentomaru":"🪓🤖","Momonga":"⚓⚔️",
"Onigumo":"🕷️⚓","Bastille":"🐂⚔️","T-Bone":"🦴⚔️","Brannew":"📰🚬","Fullbody":"🍷🥊",
"Kong":"🦍⚓","Rob Lucci":"🐆🕊️🎩","Kaku":"🦒👃","Jabra":"🐺🕶️","Blueno":"🚪🐂",
"Kumadori":"🎭💇","Fukurou":"🦉🤐","Kalifa":"🫧👓","Spandam":"🐘😤","Stussy":"🍸🦇",
"Guernica":"👊🕶️","Saint Jaygarcia Saturn":"🕷️🐄","Saint Marcus Mars":"🦅👹",
"Saint Topman Warcury":"🐗⚖️","Saint Ethanbaron V. Nusjuro":"🐎⚔️",
"Saint Shepherd Ju Peter":"🪱🌍","Saint Charlos":"👃🫧","Im":"👁️🗡️👑",
"Magellan":"☠️🧪","Hannyabal":"👺🤫","Sadi":"🔥👠","Domino":"🃏🔑",
"Monkey D. Dragon":"🌪️🔥👤","Sabo":"🎩🔥🪈","Emporio Ivankov":"💜💉👑","Inazuma":"✂️🔓",
"Belo Betty":"📣🚩","Morley":"🧌⛏️","Lindbergh":"🐱🔧","Karasu":"🐦‍⬛🎩","Koala":"🐨🥋",
"Hack":"🐟🥋","Kozuki Oden":"🍢⚔️👘","Kozuki Momonosuke":"🐉👦","Kozuki Hiyori":"🎎🎻",
"Kin'emon":"🔥👘🦊","Denjiro":"💰⚔️","Kawamatsu":"🦛🍶","Ashura Doji":"🪓😈",
"Raizo":"🥷📜","Inuarashi":"🐶🌞","Nekomamushi":"🐱🌙","Hyogoro":"👴🌸","Tama":"🍡🐒",
"Shinobu":"🥷🍑","Carrot":"🐰🥕","Wanda":"🐕‍🦺🌙","Pedro":"🐆💣","Trebol":"🤧🟢",
"Diamante":"💠🚩","Pica":"🗿🎤","Gladius":"💥🎈","Senor Pink":"👶🏊","Baby 5":"🔫💍",
"Sugar":"🧸🍇","Monet":"❄️🦅","Caesar Clown":"☠️🎈🧪","Buffalo":"🌀🏴‍☠️",
"Dellinger":"🦈👠","Jora":"🎨👵","Enel":"⚡🥁😈","Gan Fall":"🛡️🐦","Wiper":"🚀🔥",
"Conis":"🎺🦊","Nefeltari Vivi":"👸🦆💙","Karoo":"🦆👑","Nefeltari Cobra":"👑🏜️",
"Pell":"🦅🛡️","Chaka":"🐕🗡️","Igaram":"🎻👮","Dolton":"🐃❄️","Dr. Kureha":"🍒👵🩺",
"Dr. Hiluluk":"🌸💀","Boa Sandersonia":"🐍💚","Boa Marigold":"🐍🧡","Gloriosa":"👵🐍",
"Shirahoshi":"🧜‍♀️😭🐚","Neptune":"🔱🐟👑","Fukaboshi":"🦈🤴","Camie":"🧜‍♀️🐙",
"Den":"🐟🔨","Vegapunk":"🧠🔬🍭","Shaka":"🤖🧠","Lilith":"😈🔫","Edison":"💡🔧",
"Pythagoras":"📐🧮","Atlas":"🦾💪","York":"🍔🤑","Jaguar D. Saul":"🧌❄️😆",
"Dorry":"🧌🍖","Brogy":"🧌🪓","Loki":"⛓️🧌👑","Oimo":"🧌🌴","Hajrudin":"🧌🪓",
"Makino":"🍺👩","Zeff":"🦵🍳👨‍🍳","Bellemere":"🍊🚬","Nojiko":"🍊💙","Genzo":"🌀👮",
"Kaya":"🤒💰","Curly Dadan":"💇🏔️","Rouge":"🤰🌸","Shakky":"🚬🍸",
"Trafalgar D. Water Law":"💉🔪🩺","Eustass Kid":"🧲🔩🔥","Killer":"🔪🎭",
"Jewelry Bonney":"🍕⏳","Scratchmen Apoo":"🎵🥁","Basil Hawkins":"🃏🪆","X Drake":"🦖❌",
"Urouge":"🙏💪","Capone Bege":"🏰🔫🎩","Bepo":"🐻‍❄️🥋",
"Penguin":"🐧🏴‍☠️","Bartolomeo":"🛡️👹🤩","Cavendish":"🌹🐴⚔️","Sai":"🥋🐉",
"Ideo":"🥊💥","Leo":"🧵🧚","Orlumbus":"⚓🧭","Kyros":"🗡️🧸","Rebecca":"🛡️👗",
"Viola":"👁️💃"
};
