/* Titres des fiches sur One Piece Encyclopédie (onepiece.fandom.com/fr). */
const WIKI_TITLES = {
"A.A.A": "A.A.A",
"A.O": "A.O",
"Abdullah et Jeet": "Abdullah et Jeet",
"Abellon": "Abellon",
"Absalom": "Absalom",
"Accino": "Accino",
"Acheteur de Caramel": "Acheteur de Caramel",
"Acilia": "Acilia",
"Adachi Core": "Adachi Core",
"Adele": "Adele",
"Adelle Bascùd": "Adelle Bascùd",
"Adio Suerte": "Adio Suerte",
"Aegir": "Aegir",
"Agathe Toulive": "Agathe Toulive",
"Ageha Woman": "Ageha Woman",
"Agent Chocolat": "Agent Chocolat",
"Aggie 68": "Aggie 68",
"Agotogi": "Agotogi",
"Agsilly": "Agsilly",
"Aguio": "Aguio",
"Ahho Desunen IX": "Ahho Desunen IX",
"Ahho Zurako": "Ahho Zurako",
"Ahiru": "Ahiru",
"Ain": "Ain",
"Aisa": "Aisa",
"Akagami Yuki": "Akagami Yuki",
"Akainu": "Sakazuki",
"Akehende": "Akehende",
"Akibi": "Akibi",
"Akisu": "Akisu",
"Aksatanain": "Aksatanain",
"Akudai Kanzaburo": "Akudai Kanzaburo",
"Akumai": "Akumai",
"Al Hed": "Al Hed",
"Aladdin": "Aladdin",
"Alan": "Alan",
"Alba": "Alba",
"Alber": "Alber",
"Albion": "Albion",
"Alice": "Alice",
"Ally": "Ally",
"Alpagaman": "Alpagaman",
"Alpha": "Alpha",
"Alto": "Alto",
"Alvar": "Alvar",
"Alvida": "Alvida",
"Amadob": "Amadob",
"Amanda": "Amanda",
"Amazon": "Amazon",
"Amity": "Amity",
"An Zengaiina": "An Zengaiina",
"Anba": "Anba",
"Andre": "Andre",
"Angel (Personnage One-Shot)": "Angel (Personnage One-Shot)",
"Angé": "Angé",
"Anjoh": "Anjoh",
"Ankoro": "Ankoro",
"Ann": "Ann",
"Anne": "Anne",
"Ant de Bonam": "Ant de Bonam",
"Ante, Nego et Any": "Ante, Nego et Any",
"Antonio": "Antonio",
"Aoba Michiru": "Aoba Michiru",
"Aokiji": "Kuzan",
"Aphelandra": "Aphelandra",
"Apis": "Apis",
"Aremo Ganmi": "Aremo Ganmi",
"Arlong": "Arlong",
"Armored Knight": "Armored Knight",
"Arthur": "Arthur",
"Artur Bacca": "Artur Bacca",
"Aruyutayan V": "Aruyutayan V",
"Asahija": "Asahija",
"Asashichi": "Asashichi",
"Ashura Doji": "Ashura Doji",
"Aspireine": "Aspireine",
"Astrid": "Astrid",
"Aswa": "Aswa",
"Atago Niina": "Atago Niina",
"Atagoyama": "Atagoyama",
"Atlas": "Vegapunk/Atlas",
"Atmos": "Atmos",
"Atori": "Atori",
"Atsushi": "Atsushi",
"Attach": "Attach",
"Avalo Pizarro": "Avalo Pizarro",
"Axel": "Axel",
"Azuki": "Azuki",
"Azuki (non-Canon)": "Azuki (non-Canon)",
"BEZ": "BEZ",
"Babanuki": "Babanuki",
"Babe": "Babe",
"Baburu": "Baburu",
"Baby 5": "Baby 5",
"Baccarat": "Baccarat",
"Bacura": "Bacura",
"Bad One Gracie": "Bad One Gracie",
"Baggaley": "Baggaley",
"Bakezo": "Bakezo",
"Bald Parrot": "Bald Parrot",
"Balloon": "Balloon",
"Balong": "Balong",
"Balzac": "Balzac",
"Ban Dedessinée": "Ban Dedessinée",
"Banchi": "Banchi",
"Bandsman": "Bandsman",
"Bankina": "Bankina",
"Bankuro": "Bankuro",
"Banra": "Banra",
"Banzaburo": "Banzaburo",
"Banzai": "Banzai",
"Bao Huang": "Bao Huang",
"Barbara Troy": "Barbara Troy",
"Barbarossa": "Barbarossa",
"Barbe Blanche": "Edward Newgate",
"Barbe Brune": "Chadros Higelyges",
"Barbe Noire": "Marshall D. Teach",
"Barbe Rose": "Barbe Rose",
"Barbell": "Barbell",
"Bariete": "Bariete",
"Barricade": "Barricade",
"Barry": "Barry",
"Bartholomew Kuma": "Bartholomew Kuma",
"Bartolomeo": "Bartolomeo",
"Basil Hawkins": "Basil Hawkins",
"Baskerville": "Baskerville",
"Bastille": "Bastille",
"Batchee": "Batchee",
"Batman": "Batman",
"Battaman": "Battaman",
"Battler": "Battler",
"Batts Samouraï": "Batts Samouraï",
"Baxcon": "Baxcon",
"Beak Remark": "Beak Remark",
"Bear King": "Bear King",
"Bearman": "Bearman",
"Bee Anne": "Bee Anne",
"Beegirl": "Beegirl",
"Beer VI": "Beer VI",
"Beetleman": "Beetleman",
"Belladonna": "Belladonna",
"Bellamy": "Bellamy",
"Bellemere": "Bell-mère",
"Bellett": "Bellett",
"Belo Betty": "Belo Betty",
"Benn Beckman": "Benn Beckman",
"Bent": "Bent",
"Bepo": "Bepo",
"Beryl": "Beryl",
"Beurklicia": "Beurklicia",
"Biera": "Biera",
"Big Mom": "Charlotte Linlin",
"Big Pan": "Big Pan",
"Bigalo": "Bigalo",
"Bildy": "Bildy",
"Bilic": "Bilic",
"Bill": "Bill",
"Billy (Animal)": "Billy (Animal)",
"Billy (Bandit)": "Billy (Bandit)",
"Billy (Cuisinier)": "Billy (Cuisinier)",
"Billy (Pirate)": "Billy (Pirate)",
"Billy le Yabuki": "Billy le Yabuki",
"Bimine": "Bimine",
"Bingo": "Bingo",
"Binz": "Binz",
"Bishamon": "Bishamon",
"Bishonure-Onna": "Bishonure-Onna",
"Bisley": "Bisley",
"Bismarck": "Bismarck",
"Bit": "Bit",
"Biyo": "Biyo",
"Bizarre": "Bizarre",
"Björn": "Björn",
"Björn (enfant)": "Björn (enfant)",
"Black Back": "Black Back",
"Black Maria": "Black Maria",
"Blade": "Blade",
"Blakey": "Blakey",
"Blamenco": "Blamenco",
"Blenheim": "Blenheim",
"Blion": "Blion",
"Blondie": "Blondie",
"Blue Fan": "Blue Fan",
"Blue Gilly": "Blue Gilly",
"Bluegrass": "Bluegrass",
"Bluejam": "Bluejam",
"Blueno": "Blueno",
"Blumarine": "Blumarine",
"Boa Hancock": "Boa Hancock",
"Boa Marigold": "Boa Marigold",
"Boa Sandersonia": "Boa Sandersonia",
"Bobbin": "Bobbin",
"Bobby Funk": "Bobby Funk",
"Bobomba": "Bobomba",
"Bogart": "Bogart",
"Bolt": "Bolt",
"Bomba": "Bomba",
"Bomba (Marine)": "Bomba (Marine)",
"Bonbon": "Bonbon",
"Bonbori": "Bonbori",
"Bongo": "Bongo",
"Bonk Punch": "Bonk Punch",
"Bonney (Filler)": "Bonney (Filler)",
"Boo": "Boo",
"Boo Jack": "Boo Jack",
"Boo Kong": "Boo Kong",
"Boogie": "Boogie",
"Borodo": "Borodo",
"Boss": "Boss",
"Boss de la Forêt": "Boss de la Forêt",
"Bounty": "Bounty",
"Bourbon Jr.": "Bourbon Jr.",
"Braham": "Braham",
"Bran": "Bran",
"Brannew": "Brannew",
"Breed": "Breed",
"Brew": "Brew",
"Brief": "Brief",
"Brindo": "Brindo",
"Briscola": "Briscola",
"Brocca": "Brocca",
"Brogy": "Brogy",
"Brontosaurus": "Brontosaurus",
"Brook": "Brook",
"Bruce": "Bruce",
"Brululu": "Brululu",
"Bubblegum": "Bubblegum",
"Buche": "Buche",
"Buchi": "Buchi",
"Buckingham Stussy": "Buckingham Stussy",
"Buddle": "Buddle",
"Buena Festa": "Buena Festa",
"Buffalo": "Buffalo",
"Buggy": "Baggy",
"Buhichuck": "Buhichuck",
"Building Snake": "Building Snake",
"Bulldog": "Bulldog",
"Bungo": "Bungo",
"Bunny Joe": "Bunny Joe",
"Bushon et Stevie": "Bushon et Stevie",
"Busker": "Busker",
"Busshiri": "Busshiri",
"Byrnndi Byojack": "Byrnndi Byojack",
"Byrnndi World": "Byrnndi World",
"Byron": "Byron",
"Bürst": "Bürst",
"CB Galant": "CB Galant",
"Cabaji": "Cabaji",
"Caesar Clown": "César Clown",
"Caimanlady": "Caimanlady",
"Cal": "Cal",
"Camel": "Camel",
"Camie": "Camie",
"Campacino": "Campacino",
"Cancer": "Cancer",
"Candelle": "Candelle",
"Candre": "Candre",
"Cands": "Cands",
"Candy": "Candy",
"Cannon Man": "Cannon Man",
"Capone Bege": "Capone Bege",
"Capone Pets": "Capone Pets",
"Captain Kuso": "Captain Kuso",
"Captain Seven": "Captain Seven",
"Caramel": "Caramel",
"Caribou": "Caribou",
"Carina": "Carina",
"Carne": "Carne",
"Carol Masterson": "Carol Masterson",
"Carotte": "Carotte",
"Carpennya": "Carpennya",
"Carragan": "Carragan",
"Carrot": "Carrot",
"Carta (Non-Canon)": "Carta (Non-Canon)",
"Catacombo": "Catacombo",
"Catarina Devon": "Catarina Devon",
"Caucasusman": "Caucasusman",
"Cavendish": "Cavendish",
"Cello": "Cello",
"Cerbère": "Cerbère",
"Cerriot": "Cerriot",
"Cezar": "Cezar",
"Chabo": "Chabo",
"Chaka": "Chaka",
"Chameleone": "Chameleone",
"Chao": "Chao",
"Chap": "Chap",
"Chappe": "Chappe",
"Charlotte Agar-agar": "Charlotte Agar-agar",
"Charlotte Amande": "Charlotte Amande",
"Charlotte Ananas": "Charlotte Ananas",
"Charlotte Angel": "Charlotte Angel",
"Charlotte Anglais": "Charlotte Anglais",
"Charlotte Basans": "Charlotte Basans",
"Charlotte Basskarte": "Charlotte Basskarte",
"Charlotte Bavarois": "Charlotte Bavarois",
"Charlotte Brownie": "Charlotte Brownie",
"Charlotte Broyée": "Charlotte Broyée",
"Charlotte Brulee": "Charlotte Brûlée",
"Charlotte Cabaletta": "Charlotte Cabaletta",
"Charlotte Cadenza": "Charlotte Cadenza",
"Charlotte Chiboust": "Charlotte Chiboust",
"Charlotte Chiffon": "Charlotte Chiffon",
"Charlotte Cinnamon": "Charlotte Cinnamon",
"Charlotte Citron": "Charlotte Citron",
"Charlotte Compo": "Charlotte Compo",
"Charlotte Compote": "Charlotte Compote",
"Charlotte Corn Starch": "Charlotte Corn Starch",
"Charlotte Counter": "Charlotte Counter",
"Charlotte Cracker": "Charlotte Cracker",
"Charlotte Custard": "Charlotte Custard",
"Charlotte Dacquoise": "Charlotte Dacquoise",
"Charlotte Daifuku": "Charlotte Daifuku",
"Charlotte Dechat": "Charlotte Dechat",
"Charlotte Dolce": "Charlotte Dolce",
"Charlotte Dosmarché": "Charlotte Dosmarché",
"Charlotte Dragée": "Charlotte Dragée",
"Charlotte Effilée": "Charlotte Effilée",
"Charlotte Flampe": "Charlotte Flampe",
"Charlotte Galette": "Charlotte Galette",
"Charlotte Gaufrette": "Charlotte Gaufrette",
"Charlotte Hachée": "Charlotte Hachée",
"Charlotte High Fat": "Charlotte High Fat",
"Charlotte Joconde": "Charlotte Joconde",
"Charlotte Joscarpone": "Charlotte Joscarpone",
"Charlotte Katakuri": "Charlotte Katakuri",
"Charlotte Laura": "Charlotte Laura",
"Charlotte Laura/Forme Zombie": "Charlotte Laura/Forme Zombie",
"Charlotte Laurique": "Charlotte Laurique",
"Charlotte Mapple": "Charlotte Mapple",
"Charlotte Marble": "Charlotte Marble",
"Charlotte Marnier": "Charlotte Marnier",
"Charlotte Mascarpone": "Charlotte Mascarpone",
"Charlotte Mash": "Charlotte Mash",
"Charlotte Mobile": "Charlotte Mobile",
"Charlotte Mondée": "Charlotte Mondée",
"Charlotte Mont d'Or": "Charlotte Mont d'Or",
"Charlotte Mont-blanc": "Charlotte Mont-blanc",
"Charlotte Moscato": "Charlotte Moscato",
"Charlotte Mozart": "Charlotte Mozart",
"Charlotte Mucre": "Charlotte Mucre",
"Charlotte Mélisée": "Charlotte Mélisée",
"Charlotte Noisette": "Charlotte Noisette",
"Charlotte Normande": "Charlotte Normande",
"Charlotte Nougat": "Charlotte Nougat",
"Charlotte Nusstorte": "Charlotte Nusstorte",
"Charlotte Opéra": "Charlotte Opéra",
"Charlotte Oven": "Charlotte Oven",
"Charlotte Panna": "Charlotte Panna",
"Charlotte Perospero": "Charlotte Perospero",
"Charlotte Poire": "Charlotte Poire",
"Charlotte Praline": "Charlotte Praline",
"Charlotte Prim": "Charlotte Prim",
"Charlotte Pudding": "Charlotte Pudding",
"Charlotte Raisin": "Charlotte Raisin",
"Charlotte Saint-Marc": "Charlotte Saint-Marc",
"Charlotte Smoothie": "Charlotte Smoothie",
"Charlotte Snack": "Charlotte Snack",
"Charlotte Sucrage": "Charlotte Sucrage",
"Charlotte Tablette": "Charlotte Tablette",
"Charlotte Uiro": "Charlotte Uiro",
"Charlotte Yu Yuan": "Charlotte Yu Yuan",
"Charlotte Zuccotto": "Charlotte Zuccotto",
"Chat Zombie": "Chat Zombie",
"Chef (Tequila Wolf)": "Chef (Tequila Wolf)",
"Chef des Shandias": "Chef des Shandias",
"Chesskippa": "Chesskippa",
"Chessmarimo": "Chessmarimo",
"Chew": "Smack",
"Chichilisia": "Chichilisia",
"Chico (Pirate)": "Chico (Pirate)",
"Chicory": "Chicory",
"Chien-manchot": "Chien-manchot",
"Chihaya": "Chihaya",
"Chiken": "Chiken",
"Chimney": "Chimney",
"Chinjao": "Chinjao",
"Chinko Sennin": "Chinko Sennin",
"Chip et Dip": "Chip et Dip",
"Chiqicheetah": "Chiqicheetah",
"Chiya": "Chiya",
"Cho": "Cho",
"Chochinman": "Chochinman",
"Chocho": "Chocho",
"Chocolat": "Chocolat",
"Chokyumei-no Chosuke": "Chokyumei-no Chosuke",
"Chome": "Chome",
"Chouchou": "Chouchou",
"Choï": "Choï",
"Chujo": "Chujo",
"Chusuke": "Chusuke",
"Claw D. Clover": "Claw D. Clover",
"Clione": "Clione",
"Coburn": "Coburn",
"Cocoa": "Cocoa",
"Cocofox": "Cocofox",
"Coe": "Coe",
"Colscon": "Colscon",
"Comb": "Comb",
"Compo": "Compo",
"Concelot": "Concelot",
"Conis": "Conis",
"Conney": "Conney",
"Corgi": "Corgi",
"Coribou": "Coribou",
"Corlumbus": "Corlumbus",
"Cornelia": "Cornelia",
"Corto": "Corto",
"Cosette": "Cosette",
"Cosmo": "Cosmo",
"Cosmos": "Cosmos",
"Cotton": "Cotton",
"Couran": "Couran",
"Courtier animal à capuche": "Courtier animal à capuche",
"Courtier au grand chapeau de cow boy": "Courtier au grand chapeau de cow boy",
"Courtier aux longs cheveux": "Courtier aux longs cheveux",
"Courtier avec chapeau d'aviateur": "Courtier avec chapeau d'aviateur",
"Courtier avec des écouteurs": "Courtier avec des écouteurs",
"Courtier avec longues oreilles": "Courtier avec longues oreilles",
"Courtier barbu portant des lunettes de soleil": "Courtier barbu portant des lunettes de soleil",
"Courtier masqué": "Courtier masqué",
"Courtier à la cigarette": "Courtier à la cigarette",
"Courtney": "Courtney",
"Cowboy": "Cowboy",
"Craven": "Craven",
"Crocodile": "Crocodile",
"Crocus": "Crocus",
"Crown": "Crown",
"Croâtini": "Croâtini",
"Cui-Cui": "Cui-Cui",
"Cuore": "Cuore",
"Curiel": "Curiel",
"Curly Dadan": "Curly Dadan",
"Curve": "Curve",
"Cyrano": "Cyrano",
"DJ Gappa": "DJ Gappa",
"DJ Parrot": "DJ Parrot",
"Dachoman": "Dachoman",
"Dacson": "Dacson",
"Dagama": "Dagama",
"Dago": "Dago",
"Dahlia": "Dahlia",
"Daidalos": "Daidalos",
"Daifugo": "Daifugo",
"Daigin": "Daigin",
"Daikoku": "Daikoku",
"Daikon": "Daikon",
"Daisy": "Daisy",
"Daizu": "Daizu",
"Dalmatien": "Dalmatien",
"Damask": "Damask",
"Dame Arbre": "Dame Arbre",
"Dandy": "Dandy",
"Danny, Denny et Donny": "Danny, Denny et Donny",
"Daruma": "Daruma",
"Dashiteyaro": "Dashiteyaro",
"Davy D. Jones": "Davy D. Jones",
"Daz Bones": "Daz Bonez",
"Deacon": "Deacon",
"Deigoro": "Deigoro",
"Delacuaji": "Delacuaji",
"Dellinger": "Dellinger",
"Demalo Black": "Demalo Black",
"Demoni Aiyo": "Demoni Aiyo",
"Den": "Den",
"Denjiro": "Denjiro",
"Desire": "Desire",
"Dessin et Croquis": "Dessin et Croquis",
"Deuxième Acheteur de Caramel": "Deuxième Acheteur de Caramel",
"Devil Dias": "Devil Dias",
"Devilgirl": "Devilgirl",
"Diamante": "Diamante",
"Dick": "Dick",
"Didit": "Didit",
"Diego": "Diego",
"Diesel": "Diesel",
"Dieu (Personnage One-Shot)": "Dieu (Personnage One-Shot)",
"Diez Barrels": "Diez Barrels",
"Din": "Din",
"Disc J": "Disc J",
"Disco": "Disco",
"Dive": "Dive",
"Dobby Ibadonbo": "Dobby Ibadonbo",
"Doberman": "Doberman",
"Dobon": "Dobon",
"Doc Q": "Doc Q",
"Dogra": "Dogra",
"Dogya": "Dogya",
"Doha Ittanka II": "Doha Ittanka II",
"Dojaku": "Dojaku",
"Doll": "Doll",
"Dolton": "Dalton",
"Doma": "Doma",
"Domino": "Domino",
"Domo-kun et Nnke-kun": "Domo-kun et Nnke-kun",
"Don Krieg": "Krieg",
"Don Quichotte Homing": "Don Quichotte Homing",
"Don Quichotte Rossinante": "Don Quichotte Rossinante",
"Donannoyo": "Donannoyo",
"Donovan": "Donovan",
"Donquino": "Donquino",
"Donquixote Doflamingo": "Don Quichotte Doflamingo",
"Doran": "Doran",
"Doran (Hors-Série)": "Doran (Hors-Série)",
"Doringo": "Doringo",
"Dorry": "Dorry",
"Dosun": "Dosun",
"Double Down": "Double Down",
"Doubt Brothers": "Doubt Brothers",
"Douglas Bullet": "Douglas Bullet",
"Dr. Hiluluk": "Hiluluk",
"Dr. Kureha": "Kureha",
"Dracule Mihawk": "Dracule Mihawk",
"Dragon Numéro Treize": "Dragon Numéro Treize",
"Dragon Numéro Vingt-et-un": "Dragon Numéro Vingt-et-un",
"Drake": "Drake",
"Draw": "Draw",
"Dream": "Dream",
"Drip": "Drip",
"Drophy": "Drophy",
"Drug Peclo": "Drug Peclo",
"Du Feld": "Du Feld",
"Ducky Bree": "Ducky Bree",
"Duval": "Duval",
"Dédé": "Dédé",
"Démon du Destin": "Démon du Destin",
"Eboshi": "Eboshi",
"Ed": "Ed",
"Edamame": "Edamame",
"Eddy": "Eddy",
"Edison": "Vegapunk/Edison",
"Edward Weevil": "Edward Weevil",
"Egana": "Egana",
"Eggplant": "Eggplant",
"Eikon": "Eikon",
"Eisha": "Eisha",
"Ekusonhok-Adu": "Ekusonhok-Adu",
"Eldoraggo": "Eldoraggo",
"Elio": "Elio",
"Elizabello II": "Elizabello II",
"Elizabeth (Lézard)": "Elizabeth (Lézard)",
"Elmy": "Elmy",
"Emeraude": "Emeraude",
"Emil": "Emil",
"Emma": "Emma",
"Emporio Ivankov": "Emporio Ivankov",
"Enel": "Ener",
"Enfant de Makino": "Enfant de Makino",
"Enishida": "Enishida",
"Epoida": "Epoida",
"Epony": "Epony",
"Erick": "Erick",
"Erik": "Erik",
"Erik (Géant)": "Erik (Géant)",
"Eris": "Eris",
"Esther": "Esther",
"Ettara Chaunkai": "Ettara Chaunkai",
"Eunkov": "Eunkov",
"Eustass Kid": "Eustass Kid",
"Ever": "Ever",
"Fabre": "Fabre",
"Fang": "Fang",
"Farafra": "Farafra",
"Fata": "Fata",
"Fen Bock": "Fen Bock",
"Fighting Bull": "Fighting Bull",
"Fillonce": "Fillonce",
"Fishbonen": "Fishbonen",
"Fisher Tiger": "Fisher Tiger",
"Flapper": "Flapper",
"Flare": "Flare",
"Flora": "Flora",
"Footbianco": "Footbianco",
"Forliewbs": "Forliewbs",
"Fossa": "Fossa",
"Four Tricks": "Four Tricks",
"Foxaw": "Foxaw",
"Foxy": "Foxy",
"Franky": "Franky",
"Freaky Domingos": "Freaky Domingos",
"Frères Decalvan": "Frères Decalvan",
"Frères Marley": "Frères Marley",
"Frères Mizuta": "Frères Mizuta",
"Frères Risky": "Frères Risky",
"Frères Risky/Forme Zombie": "Frères Risky/Forme Zombie",
"Fuga": "Fuga",
"Fugah d'Anthier": "Fugah d'Anthier",
"Fugetsu Omusubi": "Fugetsu Omusubi",
"Fujin": "Fujin",
"Fujitora": "Issho",
"Fukaboshi": "Fukaboshi",
"Fukurokuju": "Fukurokuju",
"Fukurou": "Fukuro",
"Fullbody": "Fullbody",
"Funambules Brothers": "Funambules Brothers",
"Funkorogasun": "Funkorogasun",
"Furika": "Furika",
"Furrari": "Furrari",
"Fuza": "Fuza",
"Gabri": "Gabri",
"Gad": "Gad",
"Gage": "Gage",
"Gaimon": "Gaimon",
"Gairam": "Gairam",
"Gal": "Gal",
"Galaxy": "Galaxy",
"Galdino": "Galdino",
"Gama Pyonnosuke": "Gama Pyonnosuke",
"Gambia": "Gambia",
"Gambo": "Gambo",
"Gammon": "Gammon",
"Gan Fall": "Gan Forr",
"Gancho": "Gancho",
"Gangaru": "Gangaru",
"Gannot": "Gannot",
"Ganryu (Équipage des Pirates Roger)": "Ganryu (Équipage des Pirates Roger)",
"Ganryu (Équipage des Pirates Spade)": "Ganryu (Équipage des Pirates Spade)",
"Gantonio": "Gantonio",
"Ganzo": "Ganzo",
"Ganzui": "Ganzui",
"Gardes du Manoir": "Gardes du Manoir",
"Gardien du Destin": "Gardien du Destin",
"Gardien souterrain": "Gardien souterrain",
"Gari": "Gari",
"Garudan": "Garudan",
"Gasparde": "Gasparde",
"Gatherine": "Gatherine",
"Gattenshochinosukeo": "Gattenshochinosukeo",
"Gatz": "Gatz",
"Gazelleman": "Gazelleman",
"Gecko Moria": "Gecko Moria",
"Gedatsu": "Gedatsu",
"Geena": "Geena",
"Genbo": "Genbo",
"Genrin": "Genrin",
"Genzo": "Genzô",
"George Black": "George Black",
"George Mach": "George Mach",
"Gerd": "Gerd",
"Giberson": "Giberson",
"Gig": "Gig",
"Gild Tesoro": "Gild Tesoro",
"Gill Bastar": "Gill Bastar",
"Gimlett": "Gimlett",
"Gin": "Gin",
"Gin Rummy": "Gin Rummy",
"Ginger (Scientifique)": "Ginger (Scientifique)",
"Ginko": "Ginko",
"Ginney": "Ginney",
"Ginnosuke": "Ginnosuke",
"Gion": "Gion",
"Giovanni": "Giovanni",
"Girarin": "Girarin",
"Girash": "Girash",
"Giro Chintaro": "Giro Chintaro",
"Gismonda": "Gismonda",
"Gladius": "Gladius",
"Glass": "Glass",
"Gloriosa": "Gloriosa",
"Glove": "Glove",
"Gode": "Gode",
"Goki": "Goki",
"Gol D. Roger": "Gol D. Roger",
"Golass": "Golass",
"Goldberg": "Goldberg",
"Gonzo": "Gonzo",
"Goo": "Goo",
"Gordon": "Gordon",
"Gorilla": "Gorilla",
"Gorishiro": "Gorishiro",
"Goro": "Goro",
"Gorobe": "Gorobe",
"Gotan": "Gotan",
"Gotti": "Gotti",
"Governor": "Governor",
"Grabar": "Grabar",
"Gram": "Gram",
"Grand-Mère Barto-Club": "Grand-Mère Barto-Club",
"Grave Digger": "Grave Digger",
"Great Michael": "Great Michael",
"Grount": "Grount",
"Gu": "Gu",
"Guard": "Guard",
"Guernica": "Guernika",
"Guillotine": "Guillotine",
"Guko": "Guko",
"Gurutaro": "Gurutaro",
"Gustav": "Gustav",
"Gyanzack": "Gyanzack",
"Gyaro": "Gyaro",
"Gyoru": "Gyoru",
"Gyro": "Gyro",
"Hack": "Hack",
"Hack (Humain)": "Hack (Humain)",
"Hailey": "Hailey",
"Hajrudin": "Hajrudin",
"Hakowan": "Hakowan",
"Hakugan": "Hakugan",
"Hakuto": "Hakuto",
"Halsey": "Halsey",
"Ham Burger": "Ham Burger",
"Hamburg": "Hamburg",
"Hamlet": "Hamlet",
"Hammond": "Hammond",
"Hamu": "Hamu",
"Hana": "Hana",
"Hanafuda": "Hanafuda",
"Hanagasa": "Hanagasa",
"Hangan": "Hangan",
"Hanger": "Hanger",
"Hanji": "Hanji",
"Hanji (commerçant)": "Hanji (commerçant)",
"Hanko": "Hanko",
"Hannyabal": "Hannyabal",
"Hanzo": "Hanzo",
"Happa Yamao": "Happa Yamao",
"Happygun": "Happygun",
"Hara": "Hara",
"Harald": "Harald",
"Hardy": "Hardy",
"Haredas": "Haredas",
"Hareji": "Hareji",
"Harry (Homme-Poisson)": "Harry (Homme-Poisson)",
"Haruta": "Haruta",
"Hatcha": "Hatcha",
"Hatchan": "Octo",
"Hatsume": "Hatsume",
"Hattori": "Hattori",
"Hawkman": "Hawkman",
"Hazuki Akira": "Hazuki Akira",
"Heaby": "Heaby",
"Heat": "Heat",
"Helmeppo": "Hermep",
"Helsing": "Helsing",
"Helwett": "Helwett",
"Henna Oyag": "Henna Oyag",
"Henzo": "Henzo",
"Heppoko, Peppoko et Poppoko": "Heppoko, Peppoko et Poppoko",
"Hera": "Hera",
"Herb": "Herb",
"Herring": "Herring",
"Herz": "Herz",
"Hey": "Hey",
"Hibari": "Hibari",
"Hidayu": "Hidayu",
"Higuma": "Higuma",
"Hihimaru": "Hihimaru",
"Hikkomitsukumai": "Hikkomitsukumai",
"Hikoichi": "Hikoichi",
"Hildon": "Hildon",
"Himari": "Himari",
"Hina": "Hina",
"Hinoki": "Hinoki",
"Hip": "Hip",
"Hippan Natte": "Hippan Natte",
"Hippie": "Hippie",
"Hippo-Gentleman": "Hippo-Gentleman",
"Hiramera": "Hiramera",
"Hiro Gomon": "Hiro Gomon",
"Hiroshi": "Hiroshi",
"Hitaki": "Hitaki",
"Hitokui": "Hitokui",
"Hitsughiskhan": "Hitsughiskhan",
"Hiwa": "Hiwa",
"Hocha": "Hocha",
"Hockera": "Hockera",
"Hody Jones": "Hody Jones",
"Hoe": "Hoe",
"Hogan": "Hogan",
"Hogback": "Hogback",
"Hoichael": "Hoichael",
"Hoisassa": "Hoisassa",
"Hoisha": "Hoisha",
"Hokker": "Hokker",
"Holdem": "Holdem",
"Holy": "Holy",
"Holy (Personnage)": "Holy (Personnage)",
"Homey": "Homey",
"Honey Queen": "Honey Queen",
"Hongo": "Hongo",
"Honki": "Honki",
"Honner": "Honner",
"Hoo": "Hoo",
"Hoop Slap": "Hoop Slap",
"Hop": "Hop",
"Horo": "Horo",
"Horseman": "Horseman",
"Hotdog": "Hotdog",
"Hotei": "Hotei",
"Hotori et Kotori": "Hotori et Kotori",
"Houmy": "Houmy",
"Hound": "Hound",
"House": "House",
"Howling Gab": "Howling Gab",
"Hublot": "Hublot",
"Humphrey": "Humphrey",
"Hustle": "Hustle",
"Hyogoro": "Hyogoro",
"Hyoutauros": "Hyoutauros",
"Hyouzou": "Hyouzou",
"Héraclès": "Héraclès",
"Ian": "Ian",
"Ibiributsu": "Ibiributsu",
"Ibusu": "Ibusu",
"Icaros Mucchi": "Icaros Mucchi",
"Icebarg": "Icebarg",
"Ichiyo": "Ichiyo",
"Ida": "Ida",
"Ideaman": "Ideaman",
"Ideo": "Ideo",
"Igaram": "Igaram",
"Igaram Jr.": "Igaram Jr.",
"Iguchi Kameko": "Iguchi Kameko",
"Ihsakat EkiihsoY": "Ihsakat EkiihsoY",
"Ikkaku": "Ikkaku",
"Ikkaku (Wano)": "Ikkaku (Wano)",
"Im": "Saint Nerona Imu",
"Imuzak Akoijuf": "Imuzak Akoijuf",
"Inazuma": "Inazuma",
"Inbi": "Inbi",
"Indigo": "Indigo",
"Inhel": "Inhel",
"Inoichibannosuke": "Inoichibannosuke",
"Inuarashi": "Inuarashi",
"Inukai": "Inukai",
"Ippon Matsu": "Ippon Matsu",
"Ippon-Ume": "Ippon-Ume",
"Isa": "Isa",
"Isaac": "Isaac",
"Ishigo Shitemanna": "Ishigo Shitemanna",
"Ishilly": "Ishilly",
"Islewan": "Islewan",
"Isoka": "Isoka",
"Isuka": "Isuka",
"Iwan X": "Iwan X",
"Iwatobi": "Iwatobi",
"Izaya": "Izaya",
"Izo": "Izou",
"Jabari": "Jabari",
"Jabra": "Jabra",
"Jack": "Jack",
"Jack in the Box": "Jack in the Box",
"Jacksonbanner": "Jacksonbanner",
"Jade Ormami": "Jade Ormami",
"Jagger": "Jagger",
"Jaguar D. Saul": "Haguar D. Sauro",
"Jaki": "Jaki",
"Jango": "Jango",
"Jarl": "Jarl",
"Jean Ango": "Jean Ango",
"Jean Bart": "Jean Bart",
"Jean Goen": "Jean Goen",
"Jean Noueille": "Jean Noueille",
"Jeep": "Jeep",
"Jenfétro": "Jenfétro",
"Jericho": "Jericho",
"Jero": "Jero",
"Jerry": "Jerry",
"Jessica": "Jessica",
"Jesus Burgess": "Jesus Burgess",
"Jewelry Bonney": "Jewelry Bonney",
"Jibuemon": "Jibuemon",
"Jigoku Benten": "Jigoku Benten",
"Jigokukamabuta Megatenpanchiro": "Jigokukamabuta Megatenpanchiro",
"Jigoro": "Jigoro",
"Jigra": "Jigra",
"Jim": "Jim",
"Jimmy Myers": "Jimmy Myers",
"Jinbe": "Jinbe",
"Jiron": "Jiron",
"Jobo": "Jobo",
"Jodie et Eliza": "Jodie et Eliza",
"Johanna": "Johanna",
"John": "John",
"John Giant": "John Giant",
"Johnny": "Johnny",
"Joke": "Joke",
"Jonathan": "Jonathan",
"Jora": "Jora",
"Jorge": "Jorge",
"Joseph": "Joseph",
"Jotto": "Jotto",
"Jozu": "Joz",
"Jube": "Jube",
"Judy": "Judy",
"Jugemu Jugemuko": "Jugemu Jugemuko",
"Jujiro": "Jujiro",
"Juki": "Juki",
"Julius": "Julius",
"Jumper": "Jumper",
"Junan": "Junan",
"Kabu": "Kabu",
"Kadar": "Kadar",
"Kadoyan": "Kadoyan",
"Kagero": "Kagero",
"Kagikko": "Kagikko",
"Kaginote": "Kaginote",
"Kaido": "Kaidou",
"Kairen": "Kairen",
"Kairiken": "Kairiken",
"Kairiki Destroyers": "Kairiki Destroyers",
"Kairo Kureyo": "Kairo Kureyo",
"Kaku": "Kaku",
"Kaku (Wano)": "Kaku (Wano)",
"Kakunoshin": "Kakunoshin",
"Kalgara": "Kalgara",
"Kalifa": "Kalifa",
"Kalik Meidara": "Kalik Meidara",
"Kamakiri": "Kamakiri",
"Kamakirigirl": "Kamakirigirl",
"Kamekichi": "Kamekichi",
"Kamijiro": "Kamijiro",
"Kamonegi": "Kamonegi",
"Kamyu": "Kamyu",
"Kaneshiro": "Kaneshiro",
"Kanezenny": "Kanezenny",
"Kangourou-Zèbre": "Kangourou-Zèbre",
"Kanjuro": "Kurozumi Kanjuro",
"Kansho": "Kansho",
"Kapoty": "Kapoty",
"Kappa": "Kappa",
"Karakuri Dolls": "Karakuri Dolls",
"Karasu": "Karasu",
"Karasuke": "Karasuke",
"Kardia": "Kardia",
"Karin": "Karin",
"Karma": "Karma",
"Karoo": "Karoo",
"Kasa": "Kasa",
"Kasagoba": "Kasagoba",
"Kashigami": "Kashigami",
"Kashii": "Kashii",
"Katabuti": "Katabuti",
"Katsuzo": "Katsuzo",
"Kawamatsu": "Kawamatsu",
"Kaya": "Kaya",
"Kazekage": "Kazekage",
"Kebi": "Kebi",
"Kechatch": "Kechatch",
"Keith": "Keith",
"Kelly Funk": "Kelly Funk",
"Kent Beef Jr.": "Kent Beef Jr.",
"Kentauros": "Kentauros",
"Kerodeek": "Kerodeek",
"Kerojii": "Kerojii",
"Keroko": "Keroko",
"Keroshot": "Keroshot",
"Kiba (Erbaf)": "Kiba (Erbaf)",
"Kibagaeru": "Kibagaeru",
"Kibin": "Kibin",
"Kief": "Kief",
"Kikipatsu": "Kikipatsu",
"Kikyo": "Kikyo",
"Killer": "Killer",
"Kimel": "Kimel",
"Kimmel": "Kimmel",
"Kin'emon": "Kinemon",
"Kinbo": "Kinbo",
"Kinderella": "Kinderella",
"King": "Alber",
"King Baum": "King Baum",
"Kinga": "Kinga",
"Kingdew": "Kingdew",
"Kinno": "Kinno",
"Kinoko": "Kinoko",
"Kirin Lion": "Kirin Lion",
"Kirinkodanuki": "Kirinkodanuki",
"Kirintauros": "Kirintauros",
"Kiruko": "Kiruko",
"Kisegawa": "Kisegawa",
"Kitajima": "Kitajima",
"Kitton": "Kitton",
"Kizaru": "Borsalino",
"Koala": "Koala",
"Kobato": "Kobato",
"Kobee": "Kobee",
"Koby": "Koby",
"Koda": "Koda",
"Koito": "Koito",
"Koiwa": "Koiwa",
"Kojuro": "Kojuro",
"Kokoro": "Kokoro",
"Komachiyo": "Komachiyo",
"Komakkov": "Komakkov",
"Komane": "Komane",
"Kombu": "Kombu",
"Komei": "Komei",
"Komir": "Komir",
"Kong": "Kong",
"Kop": "Kop",
"Koron": "Koron",
"Koshi Falcon": "Koshi Falcon",
"Kourbett": "Kourbett",
"Koyama Nami": "Koyama Nami",
"Koza": "Koza",
"Koze": "Koze",
"Kozuki Hiyori": "Kozuki Hiyori",
"Kozuki Momonosuke": "Kozuki Momonosuke",
"Kozuki Oden": "Kozuki Oden",
"Kozuki Sukiyaki": "Kozuki Sukiyaki",
"Kozuki Toki": "Kozuki Toki",
"Krap": "Krap",
"Kujaku": "Kujaku",
"Kukai": "Kukai",
"Kumacy": "Kumacy",
"Kumadori": "Kumadori",
"Kumadori Yamanbako": "Kumadori Yamanbako",
"Kumagoro": "Kumagoro",
"Kuni": "Kuni",
"Kunyun": "Kunyun",
"Kuro": "Kuro",
"Kuroba": "Kuroba",
"Kuromarimo": "Kuromarimo",
"Kuroobi": "Kuroobi",
"Kurosawa": "Kurosawa",
"Kurotsuru": "Kurotsuru",
"Kurozumi Higurashi": "Kurozumi Higurashi",
"Kurozumi Orochi": "Kurozumi Orochi",
"Kurozumi Semimaru": "Kurozumi Semimaru",
"Kurozumi Tama": "Kurozumi Tama",
"Kyros": "Kyros",
"Kyuji": "Kyuji",
"Kyukyu": "Kyukyu",
"Laboon": "Laboon",
"Lacos": "Lacos",
"Lacroix": "Lacroix",
"Lacuba": "Lacuba",
"Lafitte": "Laffitte",
"Lake": "Lake",
"Laki": "Laki",
"Lambor Bukini": "Lambor Bukini",
"Lao G": "Lao G",
"Largo": "Largo",
"Lark": "Lark",
"Laskey": "Laskey",
"Lassou": "Lassou",
"LeMay": "LeMay",
"Lebno Listchaque": "Lebno Listchaque",
"Lego": "Lego",
"Lemonade Kozaru": "Lemonade Kozaru",
"Lemoncheese": "Lemoncheese",
"Leo": "Léo",
"Leonero": "Leonero",
"Lepre": "Lepre",
"Lettuce Dish": "Lettuce Dish",
"Lilith": "Vegapunk/Lilith",
"Lilly": "Lilly",
"Lily Enstomach": "Lily Enstomach",
"Limejuice": "Limejuice",
"Lina": "Lina",
"Linaria": "Linaria",
"Lindbergh": "Lindbergh",
"Lines": "Lines",
"Lion-Vache": "Lion-Vache",
"Lip Doughty": "Lip Doughty",
"Lip Shark": "Lip Shark",
"Little Oars Jr.": "Little Oars Jr.",
"Llamaman": "Llamaman",
"Loki": "Loki",
"Lola (Filler)": "Lola (Filler)",
"Lombric": "Lombric",
"Long Long": "Long Long",
"Longs-Cils": "Longs-Cils",
"Love": "Love",
"Lucky Roo": "Lucky Roux",
"Luigia": "Luigia",
"Lulis": "Lulis",
"Lulu": "Peeply Lulu",
"Luven": "Luven",
"Lytton": "Lytton",
"Lyu-Manas": "Lyu-Manas",
"M. Danbo": "M. Danbo",
"MAX Marks": "MAX Marks",
"Maccus": "Maccus",
"Mace Man": "Mace Man",
"Machi": "Machi",
"Machvise": "Machvise",
"Macro": "Macro",
"Macro (Automate)": "Macro (Automate)",
"Mad": "Mad",
"Mad Treasure": "Mad Treasure",
"Madilloman": "Madilloman",
"Mag": "Mag",
"Magellan": "Magellan",
"Magnolia": "Magnolia",
"Magra": "Magra",
"Maha": "Maha",
"Maidy": "Maidy",
"Maji": "Maji",
"Maki": "Maki",
"Makino": "Makino",
"Makko": "Makko",
"Mamy Mee et Daddy Dee": "Mamy Mee et Daddy Dee",
"Manboshi": "Manboshi",
"Mangeur d'Ile": "Mangeur d'Ile",
"Mani": "Mani",
"Manjaro": "Manjaro",
"Mansherry": "Mansherry",
"Mao": "Mao",
"Marc": "Marc",
"Marco": "Polo Marco",
"Margarita": "Margarita",
"Marguerite": "Marguerite",
"Mari": "Mari",
"Maria Napole": "Maria Napole",
"Marie": "Marie",
"Marilyn": "Marilyn",
"Marin": "Marin",
"Marin (Film Z)": "Marin (Film Z)",
"Mario": "Mario",
"Marron": "Marron",
"Marumieta": "Marumieta",
"Mashikaku (Marine)": "Mashikaku (Marine)",
"Mashikaku (Pirate)": "Mashikaku (Pirate)",
"Masira": "Masira",
"Masked Deuce": "Masked Deuce",
"Massui": "Massui",
"Mato": "Mato",
"Matsuyuki Ibuki": "Matsuyuki Ibuki",
"Maya": "Maya",
"Maynard": "Maynard",
"Mayushika": "Mayushika",
"Maître D'": "Maître D'",
"Maître des Eaux": "Maître des Eaux",
"Mc Guy": "Mc Guy",
"McKinley": "McKinley",
"Meadows": "Meadows",
"Medaka": "Medaka",
"Meganetti": "Meganetti",
"Mekao": "Mekao",
"Mendo": "Mendo",
"Mercenaires de Koala": "Mercenaires de Koala",
"Mero": "Mero",
"Meroie": "Meroie",
"Merry": "Merry",
"Meryl": "Meryl",
"Meshi (Non-Canon)": "Meshi (Non-Canon)",
"Meuh-Meuh": "Meuh-Meuh",
"Mezasuzowan Pisuo": "Mezasuzowan Pisuo",
"Miaormio Miarmani": "Miaormio Miarmani",
"Michael": "Michael",
"Mihar": "Mihar",
"Mikazuki": "Mikazuki",
"Mikio Itoo": "Mikio Itoo",
"Miles": "Miles",
"Milia": "Milia",
"Milky": "Milky",
"Millet Pine": "Millet Pine",
"Milo": "Milo",
"Minamiyama Semashi": "Minamiyama Semashi",
"Minatomo (East Blue)": "Minatomo (East Blue)",
"Minatomo (Wano)": "Minatomo (Wano)",
"Minchi": "Minchi",
"Ministre dextre": "Ministre dextre",
"Ministre sénestre": "Ministre sénestre",
"Minoru Kazeno": "Minoru Kazeno",
"Minoruba": "Minoruba",
"Minotaure": "Minotaure",
"Mint Kotori": "Mint Kotori",
"Mishoin Cashible": "Mishoin Cashible",
"Miss Catharina": "Miss Catharina",
"Miss Doublefinger": "Zala",
"Miss Father's Day": "Miss Father's Day",
"Miss Friday": "Miss Friday",
"Miss Goldenweek": "Marianne",
"Miss Monday": "Miss Monday",
"Miss Thursday": "Miss Thursday",
"Miss Valentine": "Mikita",
"Misty": "Misty",
"Misutta": "Misutta",
"Mitsuboshi": "Mitsuboshi",
"Mitsuki": "Mitsuki",
"Miucha": "Miucha",
"Miyagi": "Miyagi",
"Mizerka": "Mizerka",
"Moaï": "Moaï",
"Moaïs": "Moaïs",
"Mobambi": "Mobambi",
"Mobston": "Mobston",
"MocDonald": "MocDonald",
"Mocha": "Mocha",
"Mochie": "Mochie",
"Moda": "Moda",
"Momonga": "Momonga",
"Monda": "Monda",
"Monday (Non-Canon)": "Monday (Non-Canon)",
"Monet": "Monet",
"Monjii": "Monjii",
"Monjiro": "Monjiro",
"Monkey D. Dragon": "Monkey D. Dragon",
"Monkey D. Garp": "Monkey D. Garp",
"Monkey D. Luffy": "Monkey D. Luffy",
"Monsieur Carré": "Monsieur Carré",
"Monster": "Monster",
"Mont Blanc Cricket": "Mont Blanc Cricket",
"Mont Blanc Noland": "Mont Blanc Noland",
"Moodie": "Moodie",
"Moon Isaac Jr.": "Moon Isaac Jr.",
"Mooo...rgan": "Mooo...rgan",
"Moor": "Moor",
"Moqueca": "Moqueca",
"Morgan": "Morgan",
"Morgans": "Morgans",
"Morge": "Morge",
"Morishita Yukie": "Morishita Yukie",
"Morkin": "Morkin",
"Morley": "Morley",
"Morning": "Morning",
"Mororon": "Mororon",
"Mosh": "Mosh",
"Motobaro": "Motobaro",
"Motzel": "Motzel",
"Mounblutain": "Mounblutain",
"Mountain Ricky": "Mountain Ricky",
"Mouseman": "Mouseman",
"Mousse": "Mousse",
"Mousy": "Mousy",
"Mouthto Mouthyan": "Mouthto Mouthyan",
"Moyle": "Moyle",
"Mozambia": "Mozambia",
"Mozu et Kiwi": "Mozu et Kiwi",
"Mr 11": "Mr 11",
"Mr 13": "Mr 13",
"Mr 7": "Mr 7",
"Mr 7 (Ancien)": "Mr 7 (Ancien)",
"Mr 9": "Mr 9",
"Mr Mellow": "Mr Mellow",
"Mr. 2 Bon Clay": "Bentham",
"Mr. 5": "Gem",
"Mr. Beans": "Mr. Beans",
"Mr. Love": "Mr. Love",
"Mr. Momora": "Mr. Momora",
"Mr. Sacrifice": "Mr. Sacrifice",
"Mr. Shimizu": "Mr. Shimizu",
"Muchaner": "Muchaner",
"Muchigoro": "Muchigoro",
"Mugon": "Mugon",
"Mugren": "Mugren",
"Mukkashimi Tower": "Mukkashimi Tower",
"Mule": "Mule",
"Mummy": "Mummy",
"Musashi": "Musashi",
"Musshul": "Musshul",
"Muti": "Muti",
"Myskina Acier": "Myskina Acier",
"Myskina Livia": "Myskina Livia",
"Myskina Olga": "Myskina Olga",
"Mère de Doflamingo": "Mère de Doflamingo",
"Nagi": "Nagi",
"Najime Sound": "Najime Sound",
"Nakaiwa": "Nakaiwa",
"Nakatsugawa Usopp": "Nakatsugawa Usopp",
"Nakoh": "Nakoh",
"Nami": "Nami",
"Namur": "Namur",
"Nanagi": "Nanagi",
"Nanday": "Nanday",
"Naomi Drunk": "Naomi Drunk",
"Narcie": "Narcie",
"Narcy": "Narcy",
"Nashi": "Nashi",
"Nasu Minato": "Nasu Minato",
"Natto": "Natto",
"Nazu Ketagari": "Nazu Ketagari",
"Needless": "Needless",
"Nefeltari Cobra": "Nefertari Cobra",
"Nefeltari Vivi": "Nefertari Vivi",
"Nefertari D. Lillie": "Nefertari D. Lillie",
"Nefertari Titi": "Nefertari Titi",
"Neggy": "Neggy",
"Negikuma Maria": "Negikuma Maria",
"Neiro": "Neiro",
"Nekomamushi": "Nekomamushi",
"Nelson Royale": "Nelson Royale",
"Neoki": "Neoki",
"Nepenta": "Nepenta",
"Neptune": "Neptune",
"Nerine": "Nerine",
"Nero": "Nero",
"Nezumi": "Nezumi",
"Nico Olvia": "Nico Olvia",
"Nico Robin": "Nico Robin",
"Nigeratta": "Nigeratta",
"Nightcrab Girl": "Nightcrab Girl",
"Nightin": "Nightin",
"Nightmare Luffy": "Nightmare Luffy",
"Niina": "Niina",
"Ninth": "Ninth",
"Niphtal": "Niphtal",
"Niseluffy": "Niseluffy",
"Niseusopp": "Niseusopp",
"Nisezoro": "Nisezoro",
"Nitro": "Nitro",
"Noble Croco": "Noble Croco",
"Nodoi Wakan": "Nodoi Wakan",
"Noir": "Noir",
"Nojiko": "Nojiko",
"Noko": "Noko",
"Nokokuwa Police": "Nokokuwa Police",
"Nokotti": "Nokotti",
"Nora Gitsune": "Nora Gitsune",
"Noriko": "Noriko",
"Norinosuke": "Norinosuke",
"Nosgarl": "Nosgarl",
"Nubon": "Nubon",
"Nugire Yainu": "Nugire Yainu",
"Nukky": "Nukky",
"Nure-Onna": "Nure-Onna",
"Nuru": "Nuru",
"Nyanta": "Nyanta",
"Nypers": "Nypers",
"O-Taka": "O-Taka",
"Oars": "Oars",
"Ochinko Poro": "Ochinko Poro",
"Octopako": "Octopako",
"Odama": "Odama",
"Ohm": "Ohm",
"Oide": "Oide",
"Oignon": "Oignon",
"Oimo": "Oimo",
"Oiwa": "Oiwa",
"Okame": "Okame",
"Okohsim-Eda": "Okohsim-Eda",
"Okome": "Okome",
"Olav": "Olav",
"Olly": "Olly",
"Omasa": "Omasa",
"Onigumo": "Onigumo",
"Onimaru": "Onimaru",
"Onze Jurés": "Onze Jurés",
"Oran": "Oran",
"Orlumbus": "Orlumbus",
"Ossamondo": "Ossamondo",
"Otogin": "Otogin",
"Otohime": "Otohime",
"Ototogisu": "Ototogisu",
"Otsu": "Otsu",
"Ottoland": "Ottoland",
"Outlook III": "Outlook III",
"Oyakata": "Oyakata",
"Packi": "Packi",
"Pagaya": "Pagaya",
"Page One": "Page One",
"Palms": "Palms",
"Pandaman": "Pandaman",
"Pandawoman": "Pandawoman",
"Pankuta Dakeyan": "Pankuta Dakeyan",
"Pansy": "Pansy",
"Papa": "Papa",
"Papaneel": "Papaneel",
"Papas": "Papas",
"Pappag": "Pappag",
"Part": "Part",
"Pascia": "Pascia",
"Patrick Redfield": "Patrick Redfield",
"Patty": "Patty",
"Pauly": "Pauly",
"Pavlik": "Pavlik",
"Peanutsmonkey": "Peanutsmonkey",
"Pearl": "Pearl",
"Pedro": "Pedro",
"Pekkori": "Pekkori",
"Pekoms": "Pekoms",
"Pell": "Pell",
"Pellini": "Pellini",
"Penguin": "Penguin",
"Perona": "Perona",
"Peseta": "Peseta",
"Peterman": "Peterman",
"Petermoo": "Petermoo",
"Philip": "Philip",
"Pica": "Pica",
"Pickles": "Pickles",
"Pierre": "Pierre",
"Piglion": "Piglion",
"Pigman": "Pigman",
"Piista": "Piista",
"Pike": "Pike",
"Piment": "Piment",
"Pin Joker": "Pin Joker",
"Pincemi": "Pincemi",
"Pink Koinu": "Pink Koinu",
"Pinnacle": "Pinnacle",
"Pisaro": "Pisaro",
"Plongeurs-Outangs": "Plongeurs-Outangs",
"Pocochin Das Ehss": "Pocochin Das Ehss",
"Pogo": "Pogo",
"Poker": "Poker",
"Pokke": "Pokke",
"Polo": "Polo",
"Polo Gram": "Polo Gram",
"Pomp": "Pomp",
"Pomsky": "Pomsky",
"Popo": "Popo",
"Poppy": "Poppy",
"Porche": "Porche",
"Porchemy": "Porchemy",
"Porcupine Spike Man": "Porcupine Spike Man",
"Pork": "Pork",
"Portgas D. Ace": "Portgas D. Ace",
"Potato": "Potato",
"Potaufeu": "Potaufeu",
"Potsun": "Potsun",
"Pound": "Pound",
"Première Dame": "Première Dame",
"Prince Gles": "Prince Gles",
"Princesse des Poissons Rouges": "Princesse des Poissons Rouges",
"Princesses Matryo": "Princesses Matryo",
"Prize": "Prize",
"Prody": "Prody",
"Propriétaire d'Haraguroya": "Propriétaire d'Haraguroya",
"Propriétaire de Pasta Lake": "Propriétaire de Pasta Lake",
"Psycho P": "Psycho P",
"Pudding Pudding": "Pudding Pudding",
"Pudos": "Pudos",
"Puggy": "Puggy",
"Pukau": "Pukau",
"Puppuh": "Puppuh",
"Purin": "Purin",
"Pythagoras": "Vegapunk/Pythagore",
"Père de Wapol": "Père de Wapol",
"Queen": "Scien",
"Quincy": "Quincy",
"RENmaru": "RENmaru",
"RYU-HEY": "RYU-HEY",
"Rabbitman": "Rabbitman",
"Raideen": "Raideen",
"Raijin": "Raijin",
"Raise Max": "Raise Max",
"Raizo": "Raizo",
"Rakuda": "Rakuda",
"Rakushitemo Terusubehainaika": "Rakushitemo Terusubehainaika",
"Rakuyo": "Rakuyo",
"Ramba": "Ramba",
"Ramen": "Ramen",
"Rampo": "Rampo",
"Ran": "Ran",
"Randolph (Non-Canon)": "Randolph (Non-Canon)",
"Rangram": "Rangram",
"Rapanui Pasqua": "Rapanui Pasqua",
"Rasa": "Rasa",
"Ratchet": "Ratchet",
"Ratel": "Ratel",
"Rebecca": "Rebecca",
"Rec": "Rec",
"Red King": "Red King",
"Redwolf": "Redwolf",
"Reforto": "Reforto",
"Regis": "Regis",
"Renona Topakka": "Renona Topakka",
"Reverse": "Reverse",
"Rice-Rice": "Rice-Rice",
"Richie": "Richie",
"Rika": "Rika",
"Rikka": "Rikka",
"Riku": "Riku Doldo III",
"Rindo": "Rindo",
"Rint": "Rint",
"Rio": "Rio",
"Ripley": "Ripley",
"Ripper": "Ripper",
"Ririka": "Ririka",
"Road": "Road",
"Rob Lucci": "Rob Lucci",
"Roba": "Roba",
"Robson": "Robson",
"Roche": "Roche",
"Roche Tomson": "Roche Tomson",
"Rocks D. Xebec": "Rocks D. Xebec",
"Rockstar": "Rockstar",
"Rocky Hattari": "Rocky Hattari",
"Roddy": "Roddy",
"Roi bienveillant des vagues": "Roi bienveillant des vagues",
"Roji": "Roji",
"Rokkaku": "Rokkaku",
"Rokki": "Rokki",
"Rokuroshi": "Rokuroshi",
"Rolling Logan": "Rolling Logan",
"Romy": "Romy",
"Rongo": "Rongo",
"Ronja": "Ronja",
"Ronse": "Ronse",
"Roronoa Arashi": "Roronoa Arashi",
"Roronoa Pinzoro": "Roronoa Pinzoro",
"Roronoa Zoro": "Roronoa Zoro",
"Rosa": "Rosa",
"Roshio": "Roshio",
"Roth": "Roth",
"Rouge": "Portgas D. Rouge",
"Rowing": "Rowing",
"Roxanne": "Roxanne",
"Royder": "Royder",
"Rubis": "Rubis",
"Ruibe": "Ruibe",
"Run": "Run",
"Rush": "Rush",
"Russian": "Russian",
"Ryokugyu": "Aramaki",
"Ryuboshi": "Ryuboshi",
"Ryudo": "Ryudo",
"S-Bear": "S-Bear",
"S-Hawk": "S-Hawk",
"S-Shark": "S-Shark",
"S-Snake": "S-Snake",
"Saber": "Saber",
"Sabo": "Sabo",
"Sada": "Sada",
"Sadi": "Sadi",
"Saga": "Saga",
"Sai": "Sai",
"Saint Camael": "Saint Camael",
"Saint Charlos": "Saint Rosward Charlos",
"Saint Don Quichotte Mjosgard": "Saint Don Quichotte Mjosgard",
"Saint Don Quichotte Shivercalero": "Saint Don Quichotte Shivercalero",
"Saint Ethanbaron V. Nusjuro": "Saint Ethanbaron V. Nusjuro",
"Saint Figarland Garling": "Saint Figarland Garling",
"Saint Figarland Shamrock": "Saint Figarland Shamrock",
"Saint Jalmack": "Saint Jalmack",
"Saint Jaygarcia Saturn": "Saint Jaygarcia Saturn",
"Saint Limoshiv Killingham": "Saint Limoshiv Killingham",
"Saint Manmayer Glow": "Saint Manmayer Glow",
"Saint Marcus Mars": "Saint Marcus Mars",
"Saint Pluming": "Saint Pluming",
"Saint Rosward Rosward": "Saint Rosward Rosward",
"Saint Shepherd Ju Peter": "Saint Shepherd Ju Peter",
"Saint Shepherd Sommers": "Saint Shepherd Sommers",
"Saint Topman Warcury": "Saint Topman Warcury",
"Sainte Manmayer Gunko": "Sainte Manmayer Gunko",
"Sainte Rosward Sharlia": "Sainte Rosward Sharlia",
"Sainte Satchels Maffey": "Sainte Satchels Maffey",
"Saitank": "Saitank",
"Saki": "Saki",
"Saki (Non-Canon)": "Saki (Non-Canon)",
"Saldeath": "Saldeath",
"Sally Entoilette": "Sally Entoilette",
"Salome": "Salome",
"Sam": "Sam",
"Samosa": "Samosa",
"Sancrin": "Sancrin",
"Sandayu": "Sandayu",
"Sanji": "Sanji",
"Sanjuan Wolf": "Sanjuan Wolf",
"Saphir": "Saphir",
"Sapî": "Sapî",
"Sarahebi": "Sarahebi",
"Sarai": "Sarai",
"Sarfunkel": "Sarfunkel",
"Sarquiss": "Sarquiss",
"Sarutobi": "Sarutobi",
"Sarutobi (Non-Canon)": "Sarutobi (Non-Canon)",
"Sasaki": "Sasaki",
"Sasoz": "Sasoz",
"Satetsu": "Satetsu",
"Sato Mahiro": "Sato Mahiro",
"Satori": "Satori",
"Sauce": "Sauce",
"Savarin": "Savarin",
"Sayo": "Sayo",
"Scarlet": "Scarlet",
"Scarlett": "Scarlett",
"Schneider": "Schneider",
"Scimitarta": "Scimitarta",
"Scopper Gaban": "Scopper Gaban",
"Scorpion": "Scorpion",
"Scorpionlady": "Scorpionlady",
"Scotch": "Scotch",
"Scratchmen Apoo": "Scratchmen Apoo",
"Seagull Guns Nozdon": "Seagull Guns Nozdon",
"Seamars": "Seamars",
"Sebastian": "Sebastian",
"Seira": "Seira",
"Seki": "Seki",
"Sekken De Tearai": "Sekken De Tearai",
"Sekken De Tearai Jr.": "Sekken De Tearai Jr.",
"Sengoku": "Sengoku",
"Sennorikyuru": "Sennorikyuru",
"Senor Pink": "Señor Pink",
"Sentomaru": "Sentomaru",
"Seraphim de Crocodile": "Seraphim de Crocodile",
"Seraphim de Doflamingo": "Seraphim de Doflamingo",
"Seraphim de Gecko Moria": "Seraphim de Gecko Moria",
"Serizawa": "Serizawa",
"Serpin": "Serpin",
"Seto": "Seto",
"Shachi": "Shachi",
"Shaka": "Vegapunk/Shaka",
"Shakky": "Shakuyaku",
"Sham": "Sham",
"Shanba": "Shanba",
"Shanks": "Shanks",
"Sharinguru": "Sharinguru",
"Sheep's Head": "Sheep's Head",
"Shelly": "Shelly",
"Shepherd": "Shepherd",
"Shidou Masaru": "Shidou Masaru",
"Shiki": "Shiki",
"Shikon Kettai": "Shikon Kettai",
"Shimotsuki Furiko": "Shimotsuki Furiko",
"Shimotsuki Kozaburo": "Shimotsuki Kozaburo",
"Shimotsuki Kuina": "Shimotsuki Kuina",
"Shimotsuki Kôshirô": "Shimotsuki Kôshirô",
"Shimotsuki Ryuma": "Shimotsuki Ryuma",
"Shimotsuki Ryuma/Forme Zombie": "Shimotsuki Ryuma/Forme Zombie",
"Shimotsuki Ushimaru": "Shimotsuki Ushimaru",
"Shimotsuki Yasuie": "Shimotsuki Yasuie",
"Shine": "Shine",
"Shinobu": "Shinobu",
"Shinosuke": "Shinosuke",
"Shinpachi": "Shinpachi",
"Shioyaki": "Shioyaki",
"Shirahoshi": "Shirahoshi",
"Shiratori Tomoki": "Shiratori Tomoki",
"Shiro (Marin)": "Shiro (Marin)",
"Shirotsu": "Shirotsu",
"Shiryu": "Shiryu",
"Shishilian": "Shishilian",
"Shojo": "Shojo",
"Shorts": "Shorts",
"Shoruzô": "Shoruzô",
"Shura": "Shura",
"Shuraiya Bascùd": "Shuraiya Bascùd",
"Shushibaruba": "Shushibaruba",
"Shuzo": "Shuzo",
"Shyarly": "Shyarly",
"Shû": "Shû",
"Sicily": "Sicily",
"Sig": "Sig",
"Silk": "Silk",
"Silvers Rayleigh": "Silvers Rayleigh",
"Simon": "Simon",
"Sind": "Sind",
"Sino Phoenix": "Sino Phoenix",
"Sirènes Quintuplées": "Sirènes Quintuplées",
"Skaldi": "Skaldi",
"Skid": "Skid",
"Skull": "Skull",
"Skunk One": "Skunk One",
"Sleepy": "Sleepy",
"Smack": "Chess",
"Smash": "Smash",
"Smiley": "Smiley",
"Smoker": "Smoker",
"Smoothie (Centaure)": "Smoothie (Centaure)",
"Snakeman (Gifter)": "Snakeman (Gifter)",
"Solitaire": "Solitaire",
"Some": "Some",
"Sonier": "Sonier",
"Soo": "Soo",
"Sora (Sirène)": "Sora (Sirène)",
"Sorrow": "Sorrow",
"Spacey": "Spacey",
"Spandam": "Spandam",
"Spandine": "Spandine",
"Spartan": "Spartan",
"Spector": "Spector",
"Speed": "Speed",
"Speed Jill": "Speed Jill",
"Spencer": "Spencer",
"Spiel": "Spiel",
"Spoil": "Spoil",
"Squardo": "Squard",
"Sspaden": "Sspaden",
"Stainless": "Stainless",
"Stalker": "Stalker",
"Stansen": "Stansen",
"Stefan": "Stefan",
"Stella": "Stella",
"Stelly": "Sterry",
"Stomp": "Stomp",
"Stool": "Stool",
"Straight": "Straight",
"Strawberry": "Strawberry",
"Streusen": "Streusen",
"Stroganoff": "Stroganoff",
"Stronger": "Stronger",
"Stussy": "Stussy",
"Sugar": "Sugar",
"Suita": "Suita",
"Sukare Karehosui": "Sukare Karehosui",
"Sukare Tainen": "Sukare Tainen",
"Suke": "Suke",
"Sukoshiba Kanishitoru": "Sukoshiba Kanishitoru",
"Sukune": "Sukune",
"Suleiman": "Suleiman",
"Sunbell": "Sunbell",
"Surume": "Surume",
"Suzuki Ichiro": "Suzuki Ichiro",
"Sweetpea": "Sweetpea",
"T-Bone": "T. Bone",
"Tabi": "Tabi",
"Tabuhachiro": "Tabuhachiro",
"Tacos": "Tacos",
"Tailleur Zombie": "Tailleur Zombie",
"Tajiko": "Tajiko",
"Tajio": "Tajio",
"Takao": "Takao",
"Take": "Take",
"Taketo Nazawa": "Taketo Nazawa",
"Tama": "Kurozumi Tama",
"Tamago": "Tamago",
"Tamagon": "Tamagon",
"Tamikebao": "Tamikebao",
"Tamoshi": "Tamoshi",
"Tanaka": "Tanaka",
"Tank Lepanto": "Tank Lepanto",
"Tansui": "Tansui",
"Tapis-Ours": "Tapis-Ours",
"Tarara": "Tarara",
"Tararan": "Tararan",
"Taro": "Taro",
"Taroimo": "Taroimo",
"Tashigi": "Tashigi",
"Tay": "Tay",
"Tea IV": "Tea IV",
"Tempo": "Tempo",
"Tenjo-Sagari": "Tenjo-Sagari",
"Tensei": "Tensei",
"Tequila": "Tequila",
"Tera": "Tera",
"Terracotta": "Terracotta",
"Terry": "Terry",
"Terry Gilteo": "Terry Gilteo",
"Teto": "Teto",
"Thalassa Lucas": "Thalassa Lucas",
"Thatch": "Thatch",
"Thorman": "Thorman",
"Tigerman": "Tigerman",
"Tilestone": "Tilestone",
"Times Count": "Times Count",
"Tobio": "Tobio",
"Togare": "Togare",
"Tokijiro": "Tokijiro",
"Tokikake": "Tokikake",
"Toko": "Toko",
"Tom": "Tom",
"Tom (Cuisinier)": "Tom (Cuisinier)",
"Toma": "Toma",
"Tomac": "Tomac",
"Tomatito": "Tomatito",
"Tomato Gang": "Tomato Gang",
"Tomeo": "Tomeo",
"Tomozo": "Tomozo",
"Tonjil": "Tonjil",
"Tonjit": "Tonjit",
"Tonsfer": "Tonsfer",
"Tony Tony Chopper": "Tony Tony Chopper",
"Tori": "Tori",
"Tosa": "Tosa",
"Toto": "Toto",
"Totsu": "Totsu",
"Toyama Tsujigiro": "Toyama Tsujigiro",
"Trafalgar D. Water Law": "Trafalgar D. Water Law",
"Trafalgar Lamy": "Trafalgar Lamy",
"Trap": "Trap",
"Trebol": "Trébol",
"Tritobu": "Tritobu",
"Tritoma": "Tritoma",
"Troisième Acheteur de Caramel": "Troisième Acheteur de Caramel",
"Tsubaki (Novel)": "Tsubaki (Novel)",
"Tsugaru Umi": "Tsugaru Umi",
"Tsukimi": "Tsukimi",
"Tsunagoro": "Tsunagoro",
"Tsuru": "Tsuru",
"Tsuru (Pays des Wa)": "Tsuru (Pays des Wa)",
"Tsurube": "Tsurube",
"Tsurue Monnosuke": "Tsurue Monnosuke",
"Turco": "Turco",
"Two Base": "Two Base",
"UK": "UK",
"Ubau": "Ubau",
"Ukkari": "Ukkari",
"Ukon": "Ukon",
"Ulti": "Ulti",
"Ultraking": "Ultraking",
"Umeno Nazawa": "Umeno Nazawa",
"Umit": "Umit",
"Unforgivable Mask": "Unforgivable Mask",
"Uni": "Uni",
"Unigaro": "Unigaro",
"Urashima": "Urashima",
"Uraya Mashikatta": "Uraya Mashikatta",
"Urbain": "Urbain",
"Urban": "Urban",
"Urouge": "Urouge",
"Ushiano": "Ushiano",
"Usopp": "Usopp",
"Usunoro": "Usunoro",
"Uta": "Uta",
"Uwattsura": "Uwattsura",
"Uzu": "Uzu",
"Uzuki Namida": "Uzuki Namida",
"Uzuki Tempura": "Uzuki Tempura",
"Van Augur": "Van Augur",
"Vander Decken IX": "Vander Decken IX",
"Vasco Shot": "Vasco Shot",
"Vegapants": "Vegapants",
"Vegapunk": "Vegapunk",
"Ven Vendler": "Ven Vendler",
"Vergo": "Vergo",
"Very Good": "Very Good",
"Victoria Cindry": "Victoria Cindry",
"Victoria Shiruton Doruyanaika": "Victoria Shiruton Doruyanaika",
"Vieillard du Headband Catfish Village": "Vieillard du Headband Catfish Village",
"Vincent": "Vincent",
"Vinsmoke Ichiji": "Vinsmoke Ichiji",
"Vinsmoke Judge": "Vinsmoke Judge",
"Vinsmoke Niji": "Vinsmoke Niji",
"Vinsmoke Reiju": "Vinsmoke Reiju",
"Vinsmoke Sora": "Vinsmoke Sora",
"Vinsmoke Yonji": "Vinsmoke Yonji",
"Viola": "Riku Viola",
"Vista": "Vista",
"Vitan": "Vitan",
"Vito": "Vito",
"Volg": "Volg",
"Wadataira": "Wadataira",
"Wadatsumi": "Wadatsumi",
"Wakasa": "Wakasa",
"Wallace": "Wallace",
"Wallem": "Wallem",
"Wanda": "Wanda",
"Wanyudo": "Wanyudo",
"Wanze": "Wanze",
"Wapol": "Wapol",
"Warashi": "Warashi",
"Waruno Furishiro": "Waruno Furishiro",
"Wetton": "Wetton",
"Wheel": "Wheel",
"Whitejack": "Whitejack",
"Whitey Bay": "Whitey Bay",
"Who's-Who": "Who's-Who",
"Wicca": "Wicca",
"Wier": "Wier",
"Wilder": "Wilder",
"Willy": "Willy",
"Wind Rumor Taro": "Wind Rumor Taro",
"Wiper": "Wiper",
"Wire": "Wire",
"Wolff": "Wolff",
"Woonan": "Woonan",
"X Drake": "X Drake",
"Xiao": "Xiao",
"Yadoya": "Yadoya",
"Yama": "Yama",
"Yamada Shinichi": "Yamada Shinichi",
"Yamakaji": "Yamakaji",
"Yamamoto Luffy": "Yamamoto Luffy",
"Yamanba": "Yamanba",
"Yamato": "Yamato",
"Yame": "Yame",
"Yamenahare": "Yamenahare",
"Yaneno Chinode": "Yaneno Chinode",
"Yasopp": "Yasopp",
"Yatappe": "Yatappe",
"Yazaemon": "Yazaemon",
"Yehudi": "Yehudi",
"Yeti Cool Brothers": "Yeti Cool Brothers",
"Ylva": "Ylva",
"Yokan": "Yokan",
"Yokozuna": "Yokozuna",
"Yomo": "Yomo",
"York": "Vegapunk/York",
"Yorki": "Yorki",
"Yorle": "Yorle",
"Yorueka": "Yorueka",
"Yosaku": "Yosaku",
"Yoshimoto": "Yoshimoto",
"Yoshio": "Yoshio",
"Yoshioka Sato": "Yoshioka Sato",
"Yotsubane": "Yotsubane",
"Yu": "Yu",
"Yui": "Yui",
"Yuki": "Yuki",
"Yukimura": "Yukimura",
"Yurikah": "Yurikah",
"Zaba": "Zaba",
"Zabal": "Zabal",
"Zabo": "Zabo",
"Zadie": "Zadie",
"Zambai": "Zambai",
"Zangirimaru": "Zangirimaru",
"Zanki": "Zanki",
"Zappa": "Zappa",
"Zeff": "Zeff",
"Zeo": "Zeo",
"Zephyr": "Zephyr",
"Zepo": "Zepo",
"Zodia": "Zodia",
"Zomino": "Zomino",
"Zott": "Zott",
"Zucca": "Zucca",
"Zururin": "Zururin",
"Équilibristes": "Équilibristes"
};
